### ISSUE TITLE
Re-implement attachment support

### ISSUE THREAD

**Issue by paulhammond** [slackhq/hubot-slack#108]
The latest version of the hubot adapter fixes many things. But, there was one big regression, which is that we no longer support attachments (as originally implemented in #32).

The RTM API used by hubot-slack doesn't currently support attachments, so fixing this requires some server side changes at Slack. I'm opening this issue here so everyone knows this is something we want to fix.

**Comment by paulhammond** [comment]
The server side changes are now almost done, and I've just pushed #148 with a provisional implementation in slack-hubot... comments on the pull request are welcome

**Comment by paulhammond** [comment]
#148 is now merged, and we just released v3.3.0, so I think this is fixed!

**Comment by dblandin** [comment]
:tada::tada::tada:
