### ISSUE TITLE
Parse posted URLs for action

### ISSUE THREAD

**Issue by beardpapa** [slackhq/hubot-slack#109]
So this probably isn't the right forum to ask - but hopefully there are some elegant solutions that people can discuss!  
Previously I captured URL's mentioned in chat to pull DNS information for digestion but that stopped working after this most recent release.

For example - I would grab the url and run it through some basic regex to clean it up/remove the http, www, etc:  
`domain = (msg.match[1].replace /https?:\/\/|www\./g, "")`
Later using `$domain` in the url: http://api.statdns.com/google.com/ANY to collect the DNS data needed.

After this last update, I noticed that slack provides the URLs as either:
`<http://www.google.com|www.google.com>` or just
`<http://www.google.com>` depending on how they were entered.

Do people generally remove the brackets and split the string on the `|` character _if_ it exists?  Or is there a better method all together?

**Comment by beardpapa** [comment]
Did this change again?  As of this week I am now getting different results:

```  robot.respond /TEST (.*)/i, (msg) ->
    domain = msg.match[1]
    msg.send "`#{domain}`"```

Now returns:
```google.com http://google.com``` 
when passing it just google.com

**Comment by paulhammond** [comment]
@beardpapa: It's possible #133 might have had an effect, but the tests of this code didn't change significantly. What's the exact version of hubot-slack you're running?

**Comment by beardpapa** [comment]
Sorry, I wasn't keeping my dependency list up to date :|
Updated ```hubot-slack``` last week and it returned just the URL as expected.

Closing the issue :D
