### ISSUE TITLE
Sending formatted links doesn't work

### ISSUE THREAD

**Issue by justindowning** [slackhq/hubot-slack#114]
We switched to using hubot-slack 3.0 and am seeing weird formatting with messages that include URLs.

For example, I have a script with `msg.send "[#{url}|details]"`. The output is as follows (if `url ==https://google.com`):

v2: [details] << where details is a hyperlink in the channel
v3: [https://google.com%7Cdetails] 

I've tried `<https://google.com|details>` too, but that input is printed literally in the channel.

**Comment by omega** [comment]
Any progress or updates on this issue? We rely on a lot of formatted links in our messages, and I can't find any ways to get the 3.0 adapter to send links in a format that gets formatted correctly

**Comment by ifreecarve** [comment]
Seconded.

**Comment by justindowning** [comment]
> Unfortunately the fix for this needs some more work on our servers

@paulhammond How are things looking server-side?

**Comment by jdanlewis** [comment]
It would be nice if the link text allowed whitespace as well, e.g. <http://www.slack.com|Check it out!>.

Is there a workaround to achieve this type of formatting?

**Comment by gabriel403** [comment]
Is this getting fixed sometimes soon peeps?

**Comment by jedverity** [comment]
+1

**Comment by gampleman** [comment]
+1

**Comment by justmiles** [comment]
+1

**Comment by adambuckland** [comment]
+1

**Comment by tonglil** [comment]
+1

**Comment by heeton** [comment]
+1

**Comment by Soulfire86** [comment]
+1 Any closer to this?

**Comment by evanwolf** [comment]
+1 This also inhibits Slack's own custom slackbot responses from serving html. 

I wonder if there are security issues. Skype started analyzing all IM for evil links because of bots using Skype APIs to send phishing and malware links. Their tradeoff was "go back on our promise of end-to-end privacy" or "save our network".

**Comment by omega** [comment]
But how would evil bots get access to slack? Isn't it all private?

**Comment by warwickp** [comment]
+1

**Comment by mattdoran** [comment]
+1

**Comment by OllieJennings** [comment]
+1

**Comment by el-sonny** [comment]
+1

**Comment by sjohnr** [comment]
+1

**Comment by markisagit** [comment]
+1

**Comment by trevoro** [comment]
+1

**Comment by MaximKhorev** [comment]
+1

**Comment by augbog** [comment]
:+1:  wow took me forever to find out this was an actual issue.

**Comment by GabLeRoux** [comment]
+1 

justindowning opened this issue on 12 Dec 2014 :( Discovered hubot recently, I've been trying to make niceurls from hubot for 3 hours now telling myself that's how it's described on their api, what's wrong with my code! I was about to open a stackoverflow question then found this issue.

174 days old, sounds like I'll edit my code to give bare links instead.

> Unfortunately the fix for this needs some more work on our servers, so didn't make the cut for 3.2. We're still working on it...

Any news/plan/milestone on this?

**Comment by justmiles** [comment]
I'm not privy to any milestone updates, but I would suggest trying [Slack Attachments](https://api.slack.com/docs/attachments) before sending in bare links. It can take up more space in the chat than what's usually necessary, but it looks better.

**Comment by GabLeRoux** [comment]
thanks @justmiles, I'll give this a try. I was sending multiple links in a single message with sha in it (not very nice to the eye), but I think I can split them in multiple attachments. :)

**Comment by jbbarth** [comment]
Fwiw incoming webhooks don't have the same problem at all, so I guess that's more of an API weirdness than something else. An ETA on this would be cool :-)

**Comment by j-walker23** [comment]
Does anyone know if this is a priority? Can the public find things out like that?

**Comment by omega** [comment]
@j-walker23 you must be new around here, lol :smiley:

**Comment by j-walker23** [comment]
@omega definitely. first time i have needed to look at git issues for slack. Someone asked me how to format links in slack and i assumed it would be dead simple. I was kind of shocked when i finally landed here to see its been open for so long.

I know some companies don't publish their roadmap so they don't have to deal with the "fallout". Besides making fun of me, which i am guessing due to the first question. i laughed when i just re-read that. Being a web dev i would laugh if formatting links were a priority, but you didn't answer the question. Is there any kind of public roadmap?

**Comment by omega** [comment]
Sorry, didn't intend to make fun of you, but of slack. In the beginning they were very responsive to issues, discussing details etc, but as far as I know they have been silent the past 6 (?) months or so. 

We chose slack over competitors partly because they seemed to care about the community, but sadly I've been let down lately on that aspect of things. 

Sorry again for my inappropriate response, and to my knowledge there is no public roadmap.

**Comment by j-walker23** [comment]
ahhhh, i assumed you were calling me a noob, not them. Its sad that the internet has made me assume someone is being a dick by default. Sorry man, thanks for the reply.

That is sad, any ideas why their attitude has seemed to change?

**Comment by marco-roy** [comment]
+1

**Comment by brianantonelli** [comment]
+1

**Comment by doyle** [comment]
+1

**Comment by benbritten** [comment]
+1

**Comment by drikin** [comment]
+1
any workarund?

**Comment by benzittlau** [comment]
+1 Incredibly disappointing that this has continued to remain unfixed, and that there's not even an available workaround.

**Comment by phucnh** [comment]
+1

**Comment by kushalkadaba** [comment]
I am not using hubot, but is anybody facing this issue when sending messages with <url|label> to custom slackbot?

**Comment by trevoro** [comment]
The workaround we're currently using is to also use the webhook library, and respond with that instead for certain types of messages that require rich formatting. It seems to work fine, but it's a little ghetto.

See this gist: https://gist.github.com/trevoro/3a9dec9b001dab2ee3a0

**Comment by mmorowitz** [comment]
Suddenly, without changing my code, the channel names I publish to slack from hubot are properly linked.

**Comment by colinc** [comment]
Good grief, I literally just re-wrote a bunch of code to use attachments as a workaround.

I can confirm that `<http://www.foo.com|www.foo.com>` once again works (fixed server side by Slack). That's a relief ... after 8 months of waiting. Hopefully it'll stick around.

**Comment by justmiles** [comment]
Good to know! I'll be updating mine tomorrow.
On Aug 18, 2015 5:00 PM, "Colin" <notifications@github.com> wrote:

> Good grief, I literally just re-wrote a bunch of code to use attachments
> as a workaround.
>
> I can confirm that <http://www.foo.com|www.foo.com> once again works
> (fixed server side by Slack). That's a relief ... after 8 months of
> waiting. Hopefully it'll stick around.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/slackhq/hubot-slack/issues/114#issuecomment-132368737>
> .
>

-- 
This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the sender or system 
manager.

**Comment by GabLeRoux** [comment]
Nice, thanks for posting here, I'll update my fork of [hubot-bitbucket|https://github.com/GabLeRoux/hubot-bitbucket] :)

**Comment by timothyeburke** [comment]
Blarf! Right after I rewrote a bunch of things to use attachments.

**Comment by justmiles** [comment]
This isn't working for me. The following prints the full unformatted string.
```
msg.send "<http://www.foo.com|www.foo.com>"
```

**Comment by mmorowitz** [comment]
Just to be clear, I had formatted channel names that started working. Not external links.

**Comment by Jazcash** [comment]
You had my hopes up :(

**Comment by wkentaro** [comment]
+1

**Comment by fgeller** [comment]
+1

**Comment by ggkevinxing** [comment]
+1

**Comment by technicalpickles** [comment]
This is a duplicate of https://github.com/slackhq/hubot-slack/issues/43 . I just posted a work around there (basically, you can do it with attachments).

**Comment by wkentaro** [comment]
yeah, thanks.formatted link in text as attachments does work.

**Comment by tedsteen** [comment]
+1

**Comment by dalgard** [comment]
+1

**Comment by J3rome** [comment]
+1

**Comment by ianneub** [comment]
+1

**Comment by zakyg** [comment]
+1

**Comment by dustingregory** [comment]
+1

**Comment by adamzr** [comment]
+ 1

**Comment by itkin** [comment]
+1

**Comment by cyril** [comment]
+1

**Comment by makii42** [comment]
+1 … wow, almost a year!

**Comment by moogento** [comment]
+1

**Comment by MaximKhorev** [comment]
+1

**Comment by victor-li** [comment]
+1

**Comment by ernoaapa** [comment]
+1
How crazy is this, soon comes one year when this were opened and still no fix for this quite a basic functionality.

**Comment by jaysoncena** [comment]
+1

But isn't this a problem on Slack side? I tried sending the following directly on the chat box and it display the exact text I sent without formatting.
```
This is a link <http://google.com|google>
```

Btw, I'm using the web UI

**Comment by zakyg** [comment]
Yes, there seems to be no way to format links in Slack besides notifications, so we should probably be +1 bumping this on Slack's side somehow

**Comment by technicalpickles** [comment]
> But isn't this a problem on Slack side? I tried sending the following directly on the chat box and it display the exact text I sent without formatting.

Over on https://github.com/slackhq/hubot-slack/issues/43 I got confirmation from Slack that using RTP doesn't allow formatted links. That includes the client and the hubot adapter as it's implemented.

I also posted a workaround, which is to use attachments:

```
robot.emit 'slack.attachment', {text: "<https://github.com/link/to/a/PR|myrepo #42> fix some broken">}
```

I also have posted a PR at https://github.com/slackhq/hubot-slack/pull/236 to use `chat.postMessage` which fixes this.

**Comment by josal** [comment]
I'm using `robot.send` instead of `robot.emit` and I guess I'm not configuring the arguments properly. My origin is this:

    robot.send {room: userName}, text

How could I set the `slack.attachment` type here? I have tried this way but no success:

    robot.send {room: userName, type: 'slack.attachment'}, text

With `{text: text}` as you mention in the second argument, the message is not sent at all with `robot.send`.

Thanks in advance for your help!

**Comment by technicalpickles** [comment]
@josal you'd still use slack attachments with that branch:

```
robot.emit 'slack.attachment', {room: userName, text: "<https://github.com/link/to/a/PR|myrepo #42> fix some broken">}
```

**Comment by omeganon** [comment]
+! (original report in April 2015, here : https://github.com/slackhq/hubot-slack/issues/179)

**Comment by filmaj** [comment]
+1, guess we'll use attachments

**Comment by arminhaghi** [comment]
According to https://api.slack.com/docs/formatting#linking_to_urls
<http://www.foo.com|foo> should work, but after more than a year, still not working!

**Comment by bam0382** [comment]
+1

**Comment by andremendonca** [comment]
we can report this directly to them using this twitter account https://twitter.com/slackapi

**Comment by izikl** [comment]
+1

**Comment by nweiler** [comment]
+1

**Comment by SiebenSieben** [comment]
+1

**Comment by kevinmccartney** [comment]
+1

**Comment by dylanonelson** [comment]
+1

**Comment by infool7** [comment]
+1

**Comment by petrgazarov** [comment]
+ 1

**Comment by miketwo** [comment]
+1

**Comment by mvpgomes** [comment]
Hey guys, I am working in a feature that requires formatted links. Initially, I tried to use the message formatting described in the Slack API `<https://www.google.com|google>`, but every time I was been redirected to my Slack page. However, I tried to formatting the link in this way `<https://google.com|google>` and it worked (in my case I will receive the links without the `www`).

**Comment by nskitchgriddynamics** [comment]
+1

**Comment by corix** [comment]
+1

**Comment by TLoD-Snake** [comment]
+1

**Comment by monfera** [comment]
+1 Still doesn't work. It's not even a complicated thing once the < | > pattern and the URL is recognized, what's going on guys?

**Comment by chessracer** [comment]
+1

**Comment by adrianipopescu** [comment]
+1

**Comment by AndrewSamokhvalov** [comment]
+1

**Comment by igorpavlov** [comment]
+1 Link formatting works with slash commands, but not bots.

**Comment by nsturnitin** [comment]
Just spoke to someone at Slack that works in the Slack API group.  She asked if anyone has opened a support issue with Slack on this.  Looks like that would be the next step to get some visibility on this..

**Comment by danpollard** [comment]
+1

**Comment by augbog** [comment]
Went ahead and sent an email to feedback@slack.com. I believe someone is going to look into the issue really soon. Here is the email I got:

> So, thanks again for bringing this up with us. We discussed this a lot here, and one of our engineers will be taking a look at the issues on that repository next week. There are a couple of pull requests out that make use of another API method which allows for more advanced formatting, so we'll be reviewing those to see if they should be merged. Again, apologies for the silence from us on this — it's understandable that people are frustrated about it and we definitely should be more responsive.
> 
> — Jake

**Comment by WakeskaterX** [comment]
+1 I'm trying to rickroll a teammate and cannot :(

**Comment by hlaueriksson** [comment]
+1

**Comment by nsturnitin** [comment]
+1 to +100 has no effect.  You'll have to open a support ticket with Slack
API and post results here.

**Comment by mrcarriere** [comment]
I ran into the same issue today, and landed here from a search. After a bit of tinkering, I got it to work on my end. 

For what it's worth, this works for me on the Web API when I'm sending a message with parse="none". 

(I also send unfurl_links=False, since we're linking to our task tracker, and there's no point in constantly showing a "sign in" attachment.)

I know nothing about coffeescript, or the implementation for hubot. But for the folks who are so inclined, maybe this is a breadcrumb to get it working on your end? Good luck!

**Comment by DEGoodmanWilson** [comment]
Howdy y'all, new project maintainer here. I am looking into this this week! Hold tight, we'll get this sorted.

**Comment by JoeMattleman** [comment]
I ran into this issue trying to shorten our squad's channel topic into descriptive links.  I want: "Appear.in | JIRA Board | Confluence Page" or similar links all visible without hovering over the topic.  Thanks!

**Comment by apinnecke** [comment]
Any progress @DEGoodmanWilson? 😟

**Comment by DEGoodmanWilson** [comment]
Yes, we will have something for you soon!

**Comment by markaschneider** [comment]
Setting parse='none' (as @mrcarriere mentioned above) worked for me.

**Comment by meetravi** [comment]
+1

**Comment by korneel** [comment]
Will hyperlinking words and terms in a Slack message be supported when this ticket is closed? Because [now it's not supported](https://get.slack.help/hc/en-us/articles/202288908-Formatting-your-messages). This would be very useful for formatting [Hubot](https://hubot.github.com/) messages.

**Comment by DEGoodmanWilson** [comment]
Sorry, a bit behind on closing tickets. This should be fixed in v4. To use the feature, just follow the guide here: https://api.slack.com/docs/message-formatting

**Comment by tedsteen** [comment]
Omg. Thank you!

**Comment by rucsi** [comment]
![image](https://user-images.githubusercontent.com/2033530/34132725-8bcc7932-e451-11e7-9b56-f6d7dbe0146c.png)

**Comment by Roach** [comment]
@rucsi is the `mrkdwn_in` param being passed to specify which fields to parse as markdown?

https://api.slack.com/docs/message-formatting#message_formatting

**Comment by viveksinha** [comment]
@Roach 
This is not working for me, when the URL is sent in `text` outside the `attachments` for `chat.update` command. FYI, it works for `chat.postMessage` command and `mrkdwn` is set to `true` for both commands. I guess I'm missing something here.

**Comment by kynnjo** [comment]
FWIW, this remains broken, as of 2018-02-08.

**Comment by imTachu** [comment]
+1 @kynnjo

**Comment by viveksinha** [comment]
For me, it is working now.

**Comment by larshb** [comment]
+1

**Comment by webcat12345** [comment]
Hello everyone.
I have an issue for slack notification on Win 10.
I used slack bot and sending formatted message, <https://app.shipez.us|link>
it looks like `link` on the bot channel but display like `&lt;link&gt;` on notification.
Also it works on Mac and Ubuntu, Win 8 properly but not working on only Win 10.
![11](https://user-images.githubusercontent.com/19761422/68771207-65f94380-05dc-11ea-8213-6cd22cc326fa.png)

![12](https://user-images.githubusercontent.com/19761422/68771395-cab49e00-05dc-11ea-8b87-46c09de8a40d.png)

If anyone has a solution, please let me know.
thanks.

**Comment by Wimmmmm** [comment]
Why is this ticket being closed? The issue is still there - I cannot write manually nor via API a link with a label, to sow only the label.

**Comment by novicedev7291** [comment]
This is not working for me as well in slack client on macos x

**Comment by recursionbane** [comment]
Can confirm this is still broken. @DEGoodmanWilson, please reopen.
