### ISSUE TITLE
bot_messages should emit an event instead of being ignored

### ISSUE THREAD

**Issue by kballard** [slackhq/hubot-slack#117]
In [the code right now](https://github.com/slackhq/hubot-slack/blob/cf2db2f368355b013687a25fa44b5586231c23ad/src/slack.coffee#L68-L69) there's the following:

```node
# Ignore bot messages (TODO: make this support an option?)
return if msg.subtype is 'bot_message'
```

Perhaps this could emit an event instead, allowing scripts to be written against the slack adaptor directly.

**Comment by paulhammond** [comment]
This was fixed in #133!
