### ISSUE TITLE
SlackBot should reconnect instead of terminating the process

### ISSUE THREAD

**Issue by kballard** [slackhq/hubot-slack#127]
When the slack connection closes, or when an error occurs (which `SlackBot` currently handles by terminating the process after 1 second), the adapter should reconnect after a short timeout instead of terminating the process.

For precedent, the bundled Campfire adapter reconnects after 5 seconds when its streaming HTTP connection closes.

**Comment by michael-hopkins** [comment]
I believe this is the cause to why my hubot is shutting down on boot. We have a number of scripts all of which have been fully documented. Hubot-slack connects, and then goes to parse all the `hubot help` contents. I believe it takes longer than 10 seconds to go from `bin/hubot - a slack` to idle. I'll get a log tonight and see if that's correct

**Comment by evansolomon** [comment]
@michael-hopkins how many scripts are we talking about?  Taking 10 seconds to parse help content seems *really* surprising, that's many orders of magnitude more time that I would expect.

Also just fyi the command you pasted, `bin/hubot - a slack` has a typo.  There should not be a space between the `-` and the `a`.

**Comment by michael-hopkins** [comment]
Typo edited (mobile). I agree that it seems like a long time. I'll get some logs and see what's up

**Comment by michael-hopkins** [comment]
@evansolomon looked through the logs. On a solid bootup (no errors, and proper), it takes 7 seconds. I happened to still have the logs from when i was having issues. It looks like there was just a slight delay getting the storage from rediscloud. But 3 seconds doesn't leave a whole lot of time for a web service to be a little slow.

**Comment by ShadowRAM** [comment]
I think I am having the same or similar problem.  Hubot runs fine with the irc adapter but it has some lag so I switched to slack and it can't stay up for more than a few hours.  I have two bots and they both wind up doing this after a while:

[Sun Feb 01 2015 23:39:12 GMT-0500 (EST)] ERROR Last pong is too old: 14.997
[Sun Feb 01 2015 23:39:12 GMT-0500 (EST)] INFO Reconnecting in 1000ms
[Sun Feb 01 2015 23:39:13 GMT-0500 (EST)] INFO Attempting reconnect
[Sun Feb 01 2015 23:39:13 GMT-0500 (EST)] INFO Connecting...
[Sun Feb 01 2015 23:39:42 GMT-0500 (EST)] INFO Slack client closed

I saw elsewhere that people had success leaving the heroku keepalive script running (even when hosting elsewhere) and it seemed to make it it stay online for a little longer but still dropped the connection.

**Comment by evansolomon** [comment]
I think there are at least two fairly different issues here.

The first issue is what to do when an errors happens (e.g. the websocket connection fails somehow).  Currently the hubot adapter will kill its own process if an error makes its way from the client to the adapter.  The choice to exit the process is debatable, but I personally think it's the best choice for two reasons: it's very simple and it's actually very safe from the perspective of avoiding undefined states where the adapter thinks everything is okay but it isn't.  The downside is that the process itself is more fragile and it becomes pretty important to use a process manager (supervisor, monit, forever, etc etc).  On the other hand, it's a good idea to do that anyway.

The second issue is a particular kind of problem that (conjecture here) seems to happen when other slow processes are running (e.g. startup) or when some kind of delay/skew happens (e.g. a long delay in the ping interval that the client manages).  I haven't actually seen those myself so it's really hard to say what causes them, but one thing that seems like it could do it either a very slow synchronous process (e.g. parsing a giant JSON blob) or an event loop queue that grows very long and ends up causing wall clock delays in the pings.  Again, it's really hard to say exactly what the underlying cause for that might be, and it's probably specific to particular applications/environments.

I think it's helpful to call out those two separate things because even though they kind of manifest themselves in the same way (the hubot process dies) changing one won't necessarily affect the other.

**Comment by ShadowRAM** [comment]
I think at least from what I've seen my two bots have been idle when the got disconnected.

[Tue Feb 03 2015 11:51:20 GMT-0500 (EST)] DEBUG zzz has joined...
[Tue Feb 03 2015 13:38:38 GMT-0500 (EST)] ERROR Last pong is too old: 14.997

BTW the heroku keepalive didn't appear to help much.  One bot had it and the other didn't and both died after roughly the same amount of time.

**Comment by sdhull** [comment]
Possibly related to https://github.com/slackhq/node-slack-client/issues/5 ?

**Comment by np0x** [comment]
running on an raspberrypi is encountering the timeout on startup as well

    [Thu Feb 12 2015 03:55:16 GMT+0000 (UTC)] INFO Connecting...
    [Thu Feb 12 2015 03:55:18 GMT+0000 (UTC)] INFO Logged in as hubot of *********, but not yet connected
    [Thu Feb 12 2015 03:55:19 GMT+0000 (UTC)] INFO Slack client now connected
    [Thu Feb 12 2015 03:55:43 GMT+0000 (UTC)] INFO Data for hubot brain retrieved from Redis
    [Thu Feb 12 2015 03:55:49 GMT+0000 (UTC)] INFO Using default redis on localhost:6379
    [Thu Feb 12 2015 03:55:50 GMT+0000 (UTC)] ERROR Last pong is too old: 11.059
    [Thu Feb 12 2015 03:55:50 GMT+0000 (UTC)] INFO Reconnecting in 1000ms
    [Thu Feb 12 2015 03:55:50 GMT+0000 (UTC)] INFO Slack client closed

changing the threshold (statically set) in the client.js from 10,000 -> 20,000ms seems to be adequate in my current state to get past the threshold being set at which point the hubot starts happily.

    line 131 of node_modules/slack-client/src/client.js
                if ((_this._lastPong != null) && Date.now() - _this._lastPong > 20000) {

and with that change a successful startup

    [Thu Feb 12 2015 03:58:11 GMT+0000 (UTC)] INFO Connecting...
    [Thu Feb 12 2015 03:58:17 GMT+0000 (UTC)] INFO Logged in as hubot of *********, but not yet connected
    [Thu Feb 12 2015 03:58:18 GMT+0000 (UTC)] INFO Slack client now connected
    [Thu Feb 12 2015 03:58:42 GMT+0000 (UTC)] INFO Data for hubot brain retrieved from Redis
    [Thu Feb 12 2015 03:58:49 GMT+0000 (UTC)] INFO Using default redis on localhost:6379
    [Thu Feb 12 2015 03:58:50 GMT+0000 (UTC)] INFO Data for hubot brain retrieved from Redis


Once I am past the startup sequence all is good and stable on the device.

**Comment by danopia** [comment]
Running on a t1.micro here and hubot can't stay up more than 20 seconds. Keeps having "Last pong is too old". Changed the timeout to 20 seconds as already mentioned in the thread and our hubot works fine now.

**Comment by evansolomon** [comment]
I might worry that pongs > 10 seconds are signs of some kind of problem.  The client sends a ping every 5 seconds and Slack replies with a pong.  If the diff is greater than 10 seconds, I think those extra 5 seconds are either (1) really slow network over the websocket or (2) something blocking the event loop for a really long time.  Both of those seem like problems.

Also fwiw I have this adapter running on a t2.micro and have never seen this error :/

**Comment by danopia** [comment]
This is only an issue while Hubot starts up. Which means it never starts up
successfully. Maybe a grace period would help, t1.micros are amazingly slow.

I don't know how many people have this issue, but it shouldn't require a
code change in your module to fix :(

**Comment by evansolomon** [comment]
> it shouldn't require a code change in your module to fix

Of course.

I went back and read my first replies to this thread and I think I misunderstood the issue.  I thought the "last pong is too old" message came from an error, but apparently it's just a log message during reconnect (I realize now that this was explained way earlier, I just didn't understand it).

It seems like a decent solution would actually be to just ignore the `close` event from the slack client.  There's really no reason to exit the hubot in that case (unlike an error, where I think that is the right response).  @paulhammond any objection?

**Comment by danopia** [comment]
Yea, it seems like the first pong is delayed because of startup time. If
Hubot could not load up all over again for each reconnect, the connection
should at least stabilize quickly.

**Comment by davefp** [comment]
@evansolomon I can get behind this solution. :+1: for ignoring close altogether.
