### ISSUE TITLE
Allow hubot to mention users

### ISSUE THREAD

**Issue by paulhammond** [slackhq/hubot-slack#132]
Today you can do this in a script to cause a mention:

    msg.send "Hey <@U02871NCZ>"

Where `U02871NCZ` is the internal user id of the slack user you want to mention. But... this isn't exactly intuitive, and is unlikely to be supported by most hubot scripts. We should automatically convert `@paulhammond` to `<@U02871NCZ>` in our send function.

While we're at it, we might want to do the same for `@channel` to `<!channel>` (and group, and everyone).

**Comment by kdawgwilk** [comment]
:+1: for this feature

**Comment by tedsteen** [comment]
this is fixed nicely in #193
