### ISSUE TITLE
robot.messageRoom(chan, msg) doesn't work if chan starts with "#"

### ISSUE THREAD

**Issue by yozlet** [slackhq/hubot-slack#136]
... which wouldn't be a problem if it hadn't worked in v2, but it did, and it took a while to work out why one of my scripts wasn't working any more.

**Comment by trodrigues** [comment]
Any idea when we'll see the slack-client version updated here to fix this?

**Comment by paulhammond** [comment]
Pretty soon - we'll need to bump the version when we merge #148, so I'll likely do it at the same time

**Comment by technicalpickles** [comment]
https://github.com/slackhq/hubot-slack/pull/148 was merged, so this can be closed.
