### ISSUE TITLE
Hubot image/animate commands respond with two images

### ISSUE THREAD

**Issue by jakemauer** [slackhq/hubot-slack#142]
Hey there!

We're using Hubot in our slack rooms and when we run the following command:

`hugh animate oprah bees`

we receive two images. I looked at the Google images plugin and it seems like it should only be returning one. Is it a bug with Slack's hubot integration or with the plugin?

**Comment by evansolomon** [comment]
It only returns one for me.  Is there any chance you have two servers running the "same" bot?

**Comment by spoike** [comment]
This may happen if you accidentally added the script twice in `external-scripts.json` and `hubot-scripts.json`.

**Comment by jakemauer** [comment]
Hey guys I feel like an idiot, there were two integrations enabled. Disabling one fixed the problem. Thanks!
