### ISSUE TITLE
How can I delete a HUBOT?

### ISSUE THREAD

**Issue by mariela21180** [slackhq/hubot-slack#147]
I've added a hubot and want to remove that integration, but only allows me to disable it, not remove/delete: http://prntscr.com/5z1i3k

How can I delete it?

**Comment by jeffbyrnes** [comment]
I asked about this in a separate channel, and was informed that you cannot delete them, for reasons of history/posterity. Same way you cannot delete real users, too.

**Comment by mariela21180** [comment]
Ouch! :( Thanks for your answer... but this is ugly, because it uses an space, and I have a alert that "Your team is approaching the integration limit." Isn't there a way to force delete it? I didn't get to use it, I only installed it to test it and couldn't make it work :(

**Comment by jeffbyrnes** [comment]
@mariela21180 disabling it will stop it from counting against your integration limit. As for using a space; how do you mean? There’s no limit to the number of users you can have, as far as I’m aware.

**Comment by evansolomon** [comment]
Pretty sure @jeffbyrnes is right, disabling it should do what you need.  If not, I'm sure Slack's customer support could help.

**Comment by mariela21180** [comment]
Ok, Thank for your help :) @jeffbyrnes with space I was refering to the integrations limit.
