### ISSUE TITLE
Reply should mention user

### ISSUE THREAD

**Issue by p0deje** [slackhq/hubot-slack#167]
Hi and thanks for great plugin!

Currently, `msg.reply` will write just `username_to_reply_to:` which is only highlighted in Slack by default. Instead, hubot-slack should use mention name of user.

I've tried just prefixing it with `@`, but it seems like Slack handles mentions differently, so not sure how to implement this.

**Comment by evansolomon** [comment]
> which is only highlighted in Slack by default

I don't think I understand this.  Are you saying it should not be highlighted?  Or that it should be highlighted *and* something else?

> it seems like Slack handles mentions differently

Can you expand on this a bit?  What happened when the name was prefixed with "@"?

**Comment by p0deje** [comment]
Sorry about the bad bug report.

That's how a `msg.reply` looks in Slack:

![screen shot 2015-03-18 at 00 19 10](https://cloud.githubusercontent.com/assets/665846/6694419/0c84ad1c-ccfc-11e4-9d18-d66b18670147.png)

As you can see, it's highlighted (since `p0deje` is my username), but it's not actual mentioning (like on the following screenshot).

![screen shot 2015-03-18 at 00 18 36](https://cloud.githubusercontent.com/assets/665846/6694407/f613e5d4-ccfb-11e4-9487-7013fc4c2f1c.png)

**Comment by evansolomon** [comment]
Oh, I get it now.  Thanks for clarifying.

**Comment by abusalimov** [comment]
This is likely to be related with #132 as well as #119, I guess.
