### ISSUE TITLE
Hubot no response

### ISSUE THREAD

**Issue by lukezheng** [slackhq/hubot-slack#178]
At sometime between 9:15am to 10:07am PDT 4/13/15 our hubot on Heroku stopped responding.

I see in my heroku logs 

```
2015-04-13T02:57:14.835723+00:00 heroku[router]: at=info method=POST path="/hubot/slack-webhook" host=safe-woodland-3073.herokuapp.com request_id=80dbd2cc-1f86-4b4e-84c9-88ab3145bb3e fwd="54.164.116.8" dyno=web.1 connect=1ms service=13ms status=200 bytes=135
2015-04-13T02:57:14.827306+00:00 app[web.1]: Incoming message received
```
but nothing gets relayed back to slack.  I also don't see the loglines that's part of the hubot script I wrote (it does printout when working before 9:15am).

I tried restarting my heroko dyno, but nothing worked.  Did something change on slack's end?

**Comment by joshsz** [comment]
Looks like I'm having the same problem

**Comment by joshsz** [comment]
I figured it out, Slack upgraded to a new API to interact with Hubot. You have to recreate your integration to get an API token that starts with xoxb- or something and then /invite your bot into any channel you want it in. Good luck!

**Comment by lukezheng** [comment]
@joshsz I tried doing that as well, but now Hubot doesn't even respond.

**Comment by lukezheng** [comment]
@joshsz nvm!  Looks like I had to force update my hubot-slack package.
