### ISSUE TITLE
BlackList / WhiteList Channels

### ISSUE THREAD

**Issue by CorbanR** [slackhq/hubot-slack#180]
It would be nice to have the ability to only accept / respond to Whitelisted slack channels.

**Comment by evansolomon** [comment]
Huots only listen in channels they are invited to. So inviting the bot == whitelisting and not inviting it == blacklisting.

**Comment by CorbanR** [comment]
I was hoping for the ability to limit access either by channel or specific users.

**Comment by evansolomon** [comment]
I don't think I 100% understand what you mean. Is not having a bot in a channel be an example of limiting access by channel, or do you want something else?  If you want to permission user access, the [hubot-auth](https://github.com/hubot-scripts/hubot-auth) plugin might work well for you.

**Comment by bitflingr** [comment]
This is not the case for #general which is very annoying when you have a large amount of people in there.
