### ISSUE TITLE
Can hubot to notify all in a channel when using `@channel`

### ISSUE THREAD

**Issue by BlueHatbRit** [slackhq/hubot-slack#189]
I've been searching around the open and closed issues and I can't seem to find the answer. Our team setting is to always confirm if you wish to send a `@channel` message. With hubot is there any way to remove this restriction or anything in the adapter to mean that he will automatically accept that confirmation?

We're using him for some notifications which we would like entire channels to be aware of (a new issue to do with X and stand up notifications etc) so it's something we'd like to use a fair bit, but only for Hubot.

**Comment by ShadowRAM** [comment]
This may be related to my issue.  Do you have @group/@channel restricted to admin/owners only? https://github.com/slackhq/hubot-slack/issues/149

**Comment by BlueHatbRit** [comment]
Yes it is, I shall close this as it's a duplicate!
