### ISSUE TITLE
Link names no longer working

### ISSUE THREAD

**Issue by briwa** [slackhq/hubot-slack#201]
Hi, I noticed that in the latest version of hubot-slack, the link names are no longer working. Back then we can just specify `HUBOT_SLACK_LINK_NAMES=1` and all the `<@U1231|aa>` or `<http://www.google.com/Google>` will wrap up itself and become links. I can't seem to do it in this version. Is there something I have missed?

Thanks.

**Comment by omega** [comment]
This is the same as #114 I think?

**Comment by igorpavlov** [comment]
Omega is right, dup of #114
