### ISSUE TITLE
Private message a user if no conversation has been started yet.

### ISSUE THREAD

**Issue by joeyhipolito** [slackhq/hubot-slack#204]
I can send private message to a user same a as how I send message to a room like so:

    module.exports = (robot) ->
      robot.router.post "/hubot/say", (req, res) ->

        room = req.body.room
        message = req.body.message

        robot.logger.info "Message '#{message}' received for room #{room}"

        user = robot.adapter.userForId 'broadcast'
        user.room = room
        user.type = 'groupchat'

        if message
          robot.send user, "#{message}"

        res.writeHead 200, {'Content-Type': 'text/plain'}
        res.end 'Thanks\n'

**BUT** I can only send private message to people who actually have a conversation with the bot beforehand, and I cannot send private messages to people who aren't **yet**.

How can I send private messages to all users, without needing them to message the bot first.

Thanks!

**Comment by suhasgaddam** [comment]
From this commit [1156fd60baa63de63e3c44aa1253c85e4b16b2b1] onwards, you can private message any user.

**Comment by joeyhipolito** [comment]
@suhasgaddam thanks, let me take a look at that on implement that base on that one :)

**Comment by DEGoodmanWilson** [comment]
I believe this should no longer be an issue, so I am closing as resolved.
