### ISSUE TITLE
next release date?

### ISSUE THREAD

**Issue by silarsis** [slackhq/hubot-slack#208]
There's a patch in the current code - for opening new DMs to people - that I really need, but last release was a while ago so yeoman's pulling in an old version. Any idea when the next release is likely to be?

Thanks,

**Comment by mshwery** [comment]
+1

**Comment by optical** [comment]
:+1: Just got bitten by the bug mentioned, would be nice to have the version with the change on npm

**Comment by Ferrari** [comment]
+1

**Comment by jgonera** [comment]
I'd love to see this released too.

**Comment by jgonera** [comment]
I would really appreciate any information on this. Are we waiting for some other PRs to be merged? Any approximate date?

**Comment by mshwery** [comment]
Looks like there's a new release _but_ hasn't been published to npm yet!

**Comment by mjsz** [comment]
Sorry for the oversight -- the latest version has been published.
