### ISSUE TITLE
Wrap Slack web API methods?

### ISSUE THREAD

**Issue by ORBAT** [slackhq/hubot-slack#209]
I made a small wrapper for the Slack web API methods, and I figure it might be useful functionality for the adapter itself ~~(it'd help with #202, for example.)~~ Should I work on a PR for this, or does it make more sense to keep `hubot-slack-api` separate?

**Edit (5 Jul)**: Nevermind, I'm an idiot, `channels.leave` can't be called by bots. That's a bit silly.

**Comment by technicalpickles** [comment]
The adapter has an instance of a [node-slack client](https://github.com/slackhq/node-slack) as `client`. You should be able access it at `robot.adapter.client`.

Possible relevant, but I'm experimenting with a custom `response` object over in https://github.com/slackhq/hubot-slack/pull/234 so a script can do a Slack-specific response in scripts. There's only attachment, but some API commands might be relevant.

**Comment by technicalpickles** [comment]
Closing, since there is a way to call the API. I'm going to make a note to include documentation though.
