### ISSUE TITLE
check if  slack-attachment custom data is successful

### ISSUE THREAD

**Issue by ambikads** [slackhq/hubot-slack#216]
I use slack-attachment to send custom messages to channels. How do I get the return code for this to check if the channel did successfully receive user's message? Essentially I need to check if the slack returned {ok: true} after this function is executed. Any idea how can I do this? Thanks

someFunction = (robot, user, channel, text) ->
    robot.emit 'slack-attachment', {
      username: user,
      channel: channel,
      text: text
    }

**Comment by technicalpickles** [comment]
There isn't a good way to do this. When you emit the 'slack-attachment', `customMessage` is the handler for it: https://github.com/slackhq/hubot-slack/blob/master/src/slack.coffee#L254-L281

I think it could be considered an oversight with hubot's original design, but a lot of the functions for sending data back to a user are 'fire and forget'. That is, they happen asynchronously, but the API doesn't support an API for checking the result. That'd be a good improvement in general I think, but it could implementation might be tricky to keep backwards compatibility.

I'm sure I know the answer, but what were you trying to check the return code for? Were you seeing messages not actually get delivered?

**Comment by DEGoodmanWilson** [comment]
We are going to remove this event from the next release, and instead have you just send messages with attachments through the usual mechanism, which should obviate this problem. Closing for now.

**Comment by anupdhml** [comment]
@DEGoodmanWilson do you know how long it will be until the next release?

We want to use hubot to deliver alerts on site errors but right now, there is no way to know for sure if the delivery succeeded or not. Having a return code from the message sending function would help us degrade gracefully to other alert paths (or retry the hubot alert), so that we don't miss potential critical alerts.

**Comment by DEGoodmanWilson** [comment]
I don't have a schedule yet, but have a look at #309 for the bleeding-edge branch.
