### ISSUE TITLE
installation challenges with coffeescript

### ISSUE THREAD

**Issue by mikeatlas** [slackhq/hubot-slack#220]
I had to do the following to get specific versions of `coffee-script` and `coffee-jshint` installed globally before I could proceed:

`sudo npm install coffee-script@1.8.0 coffee-jshint@0.2.2 -g` 

Consider perhaps upgrading these to newer stable versions in `hubot-slack`? 

Even as such, I still get errors:

```
npm ERR! peerinvalid The package coffee-script@1.9.3 
 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer coffee-jshint@0.2.2 wants coffee-script@>= 1.6 <= 1.8.0`
```

Finally, got it to install via:

`sudo npm install -g hubot coffee-script@1.8.0 coffee-jshint@0.2.2 yo generator-hubot`

**Comment by technicalpickles** [comment]
> I had to do the following to get specific versions of coffee-script and coffee-jshint installed globally before I could proceed:

What were you doing specifically, ie were you generating a bot, or just running it? What was happening before getting the specific versions?

That said, I'm not sure if this is necessarily a problem with hubot-slack. It only has one (direct) dependency: `slack-client`. It'd  probably be better to file it with http://github.com/github/hubot with that info if you don't mind.

**Comment by DEGoodmanWilson** [comment]
Closing as off-topic.
