### ISSUE TITLE
Unreleased changes

### ISSUE THREAD

**Issue by technicalpickles** [slackhq/hubot-slack#228]
There is a number of merged, but unreleased changes: https://github.com/slackhq/hubot-slack/compare/3.3.0...master . Is there an intention to create a release with those changes?

**Comment by jgonera** [comment]
Yes, please, I'm really interested in https://github.com/slackhq/hubot-slack/issues/204.

**Comment by technicalpickles** [comment]
This is actually a duplicate of https://github.com/slackhq/hubot-slack/issues/208
