### ISSUE TITLE
Hubot respond only in specific channel/private room

### ISSUE THREAD

**Issue by mbadura** [slackhq/hubot-slack#231]
Hi.
I'm writing my first hubot scrpt , and i'am looking for solution to make hubot listen or respond only in specific channel / private room. Is that possible ?

**Comment by technicalpickles** [comment]
These some discussion over in https://github.com/slackhq/hubot-slack/issues/214 about this.

**Comment by mbadura** [comment]
Yes but i was thinking more like whitelist for commands not for whole bot itslef.

**Comment by technicalpickles** [comment]
That's not what you asked initially :grin: 

You can use listener middleware for that as talked about over there for command whitelisting. Also worth noting that's more general hubot, than hubot-slack.

**Comment by DEGoodmanWilson** [comment]
Closing as off-topic / resolved.
