### ISSUE TITLE
hidden characters?

### ISSUE THREAD

**Issue by mhigley** [slackhq/hubot-slack#238]
When copying sass to be compiled out of either the browser or app, it appears to contain some invisible characters which causes compilation to error. Viewing as raw results in no errors.

**Comment by technicalpickles** [comment]
I'm not sure I follow. Is this about hubot-slack, or something else Slack related?

**Comment by DEGoodmanWilson** [comment]
As there is no CSS in `hubot-slack`, marking as off-topic and closing.
