### ISSUE TITLE
`messageRoom` and `send` should support `channel_id` in addition to `channel_name`

### ISSUE THREAD

**Issue by jeffreywescott** [slackhq/hubot-slack#243]
This is problematic when used with [HTTP Listeners](https://github.com/github/hubot/blob/master/docs/scripting.md#http-listener) for [Slack Slash Commands and Incoming Web Hooks](https://api.slack.com/slash-commands), since the `POST` data passed along from the slash command doesn't necessarily include a valid `channel_name`. Specifically, in the case of Private Groups, the `channel_name` that comes along is simply `'privategroup'`.

I think given the fact that Slack has this dual-notion of "ID" and "name" for users, channels, etc., the adapter should be smart enough to handle either. That is, first check to see if it's a valid ID. If not, check to see if it's a valid name. If not, then abort. Right now, it's just assuming that it's a name, making it pretty much impossible to use Hubot for Slash Commands.

**Comment by mjsz** [comment]
now included in 3.4.1. please verify and close at your convenience!

**Comment by jeffreywescott** [comment]
Verified that this is working. Thanks for the merge!
