### ISSUE TITLE
Intercept and format user messages

### ISSUE THREAD

**Issue by SpencerKaiser** [slackhq/hubot-slack#247]
Is it possible to intercept user messages and prepend/append text to them? Ideally I'd like to take every message coming in and, depending on the user, prepend text to their message (like a user ID) before allowing the message to reach the channel/private chat.

(Sorry if this is the wrong place to ask questions like this!)

**Comment by technicalpickles** [comment]
@SpencerKaiser if I'm understanding you right, you want hubot to receive messages from users, and depending on the user, change the message before it's delivered to the room?

If that's the case, I don't think it's possible, as the message is reaching both the channel/private chat at the same time that hubot is receiving it.

Or, do you mean, when sending messages back to users, you'd like to append something to the hubot message the user will receive? That would be possible with [hubot response middleware](https://github.com/github/hubot/blob/master/docs/scripting.md#response-middleware)

**Comment by SpencerKaiser** [comment]
Hey @technicalpickles Thanks for the response! Since I posted this question I've given up, but yea it was the former and I figured it was not possible.
