### ISSUE TITLE
hubot does not wake up on Heroku when I ping it 

### ISSUE THREAD

**Issue by magicstone1412** [slackhq/hubot-slack#249]
I installed hubot for slack from win 10. Everything works well until the bot was put in sleep mode. I can not ping it to wake it up even if I set URL var in Heroku Config Vars. I accessed it via url and it woke up. How can I solve my problem? Thank you.

**Comment by SammyIsra** [comment]
+1, I've been having this issue too.

**Comment by evansolomon** [comment]
I'd recommend checking out the main heroku keepalive repo here https://github.com/hubot-scripts/hubot-heroku-keepalive

**Comment by SammyIsra** [comment]
I'm currently on it, but it is not working for some (yet) unknown reason.

**Comment by evansolomon** [comment]
Sorry to hear that. That's definitely the best place to figure it out.

Just to clarify one important thing, it's not really the *bot* that's sleeping, it's the *server* (technically the "dyno"). It doesn't really have anything to do with Hubot or a particular adapter, it just so happens that a lot of people use Heroku to run Hubot instances and Heroku uses this sleep concept to manage their resources.

**Comment by technicalpickles** [comment]
This is an issue with the hubot-heroku-keepalive, not hubot-slack. Can you (or anyone else) running into problems keeping Heroku alive [file an issue there please](https://github.com/hubot-scripts/hubot-heroku-keepalive)?
