### ISSUE TITLE
Get room's topic

### ISSUE THREAD

**Issue by defenestration** [slackhq/hubot-slack#252]
I've been looking for a way to get the current room or a room's topic.

I found i can grab it when the topic is changed with the robot.topic function and have been storing it that way.  Just wondering if there is an easier method. 

Edit: This might just be a hubot limitation in general from the hubot scripting doc? Not sure.

**Comment by DEGoodmanWilson** [comment]
Closing on the premise that this is a Hubot issue, and not specific to Slack. Please re-open if it turns out I am mistaken.
