### ISSUE TITLE
Testing attachment in the shell?

### ISSUE THREAD

**Issue by tleunen** [slackhq/hubot-slack#254]
Is there a way to test the slack attachment (custom message) in the shell?
For some reasons, all my attempts were unsuccessful, but maybe I do something wrong. Any example would be nice if this is something possible.

**Comment by justmiles** [comment]
I don't believe there is. The slack attachment is specific to the slack adapter. When using the shell adapter the ability to emit slack attachments simply isn't there.

For some of my scripts I've added logic to test for a slack adapter before attempting to emit an attachment. This, of course, defaulting to sending an unformatted messaged if the adapter doesn't exist.

**Comment by justmiles** [comment]
Here's an example
```coffee
if robot.adapterName == 'slack'
    robot.emit 'slack-attachment',
      message: msg
      content: mySlackAttachment
else
  msg.send "An alternative message"
```

**Comment by DEGoodmanWilson** [comment]
You can of course always use [Message Builder](https://api.slack.com/docs/messages/builder) to test out your messages.

Closing as resolved.
