### ISSUE TITLE
Hubot Is Typing

### ISSUE THREAD

**Issue by dwlt** [slackhq/hubot-slack#259]
Are there any plans to support the "... is typing" message type for Hubot? This would be really useful for some of the longer-lived ChatOps type commands I've been working on to indicate that something is happening behind the scenes.

I've had a quick experiment with trying to make it work by sending a custom message (as with sending an attachment), but not had any joy, so thought I'd open the question up to see if this is something anyone else has attempted.

**Comment by technicalpickles** [comment]
There was some discussion about it over in https://github.com/github/hubot/issues/1023 but nothing concrete happened.

It looks like this is the relevant RTM event: https://api.slack.com/events/user_typing .  `robot.adapter.client` is an instance of https://github.com/slackhq/node-slack-client if you can figure out how to send that event back over it.

**Comment by bkchan** [comment]
I ran into this same problem using [python-slackclient](https://github.com/slackhq/python-slackclient).  [This page](https://medium.com/@kipsearch/3-things-we-learned-building-a-chatbot-for-slack-2dc32321d77c#.rbas0dwgs) (scroll down) has some details on how to do this, but you just need to send a custom JSON object with `type` set to `'typing'`, `channel` set to the channel ID where the bot is "typing," and `id` set to `1` over the RTM connection.

**Comment by dasilvacontin** [comment]
This would be cool indeed. :)

**Comment by RIAlizer** [comment]
I think I found a workaround to add this feature
please check my PR
https://github.com/slackhq/hubot-slack/pull/281

**Comment by DEGoodmanWilson** [comment]
@technicalpickles has the right idea. This _might_ be fixed in the latest `node-slack-sdk`, marking as such.

**Comment by DEGoodmanWilson** [comment]
Closing this as fixed in 4.0. Please reopen if I am mistaken!
