### ISSUE TITLE
Hubot doesn't respond to messages from integrations/bots

### ISSUE THREAD

**Issue by mrkrumhausen** [slackhq/hubot-slack#260]
Hubot doesn't respond to trigger words posted using other integrations/bots/webhooks.

**Comment by ndaversa** [comment]
@mrkrumhausen Were you able to get around this problem? If so, how?

**Comment by mrkrumhausen** [comment]
No, it's to avoid infinite loops.

**Comment by ndaversa** [comment]
@mrkrumhausen I was able to get around this by listening to all messages, which include the bot messages

**Comment by mrkrumhausen** [comment]
Cool. How?

**Comment by ndaversa** [comment]
https://github.com/github/hubot/blob/master/docs/patterns.md#dynamic-matching-of-messages

**Comment by ndaversa** [comment]
I should be clear. It doesn't get its own messages with this. Which is a good thing. Infinite loops and such

**Comment by mrkrumhausen** [comment]
Awesome. Thanks!
