### ISSUE TITLE
After disabling and enabling Hardware Acceleration, fullscreen settings remains. 

### ISSUE THREAD

**Issue by dmxt** [slackhq/hubot-slack#263]
I used to have preference windows as a modal. After disabling Hardware Acceleration and restart, preference became a fullscreen window:

[Screenshot of fullscreen preferences](http://vgy.me/voaC2H.png)

After enabling Hardware Acceleration and restart, preference is still a fullscreen window instead of modal. 

How do I revert preferences back to a normal modal like before?

**Comment by technicalpickles** [comment]
@dmxt it looks like you are having problems with the Slack client, not the hubot-slack adapter. You can use `/feedback` from the client, email feedback@slack.com, or visit https://slack.com/help/contact to get help.
