### ISSUE TITLE
reply_to and room values incorrect?

### ISSUE THREAD

**Issue by parkr** [slackhq/hubot-slack#266]
Hey, working through a strange bug. Sorry for the vague title and message, but not sure what is going on here. Having trouble integrating [hubot-tell](https://github.com/hubot-scripts/hubot-tell) with Slack because the `reply_to` and `room` fields differ.

`reply_to` is some strange alphanumeric string which I _think_ encodes both the sender _and_ the room. The room is, of course, just the channel name without the preceding `#`.

To understand the issue I'm having, please see https://github.com/hubot-scripts/hubot-tell/issues/7, which describes the discrepancy. hubot-tell uses the `reply_to` field because it is necessary for the hubot-hipchat adapter. Apparently, this breaks hubot-slack which should be using the `room` instead of the `reply_to`. One of them is backwards or the bug is elsewhere, but I'm unable to pinpoint exactly which.

Any guidance you can provide would be greatly appreciated!

**Comment by DEGoodmanWilson** [comment]
Looks like this is a duplicate of #150, I'm going to close this one, and pick of the conversation there. Join me, @parkr?
