### ISSUE TITLE
Moderation bot

### ISSUE THREAD

**Issue by Exuviax** [slackhq/hubot-slack#273]
Hey,

I run a very public slack and we are looking for a way to moderate the chat (much like Moobot on twitch) the ability to timeout users (delete all their messages hey send in any channel or specific channel for a period of time), ban users, delete messages with trigger words (profanity), and personal message users (regardless of open dm or not) who have violated rules (or ability to send the "only you can see this" messages)

I'm more looking to see if this adapter has the ability to do some of these things, like check which channel it's in and check the users Id, for bans and deletions. Also deleting messages of users other then the bot.

Thanks :)

**Comment by bbuck** [comment]
I'm no expert, but having implemented Hubot for a few different services I'd assume this project is primarily filling the "adapter" interface to allow Hubot to connect and perform standard actions (reading and responding to messages). I doubt the advanced features you want are included. But you could easily make a plugin for the bot that performs those actions via the Slack API and having Hubot do any automatic monitoring, etc... that you want to include. You can also add commands (limiting access via hubot-auth) that allow moderators to tell hubot to ban a user and after receiving the command hubot can go about banning the user following whatever specific process you desire.

**Comment by DEGoodmanWilson** [comment]
By and large, anything that you can do with the Slack SDK is available through this adapter, or via the underlying Slack SDK! Closing as resolved.
