### ISSUE TITLE
Users, channels with non-alphanumeric characters are not mentioned

### ISSUE THREAD

**Issue by abesto** [slackhq/hubot-slack#275]
I'm only 80% sure my diagnosis is correct; looking at what I've seen so far and https://github.com/slackhq/hubot-slack/blob/master/src/slack.coffee#L229 (especially the `\w` part), it looks like for example channels with dashes in them and users with dots in their names are not linked.

**Comment by antoineco** [comment]
Also facing that issue with names containing dots:

--
![kitchen](https://cloud.githubusercontent.com/assets/3299086/13697757/e008405c-e76f-11e5-9b6f-6c1ab075754d.png)

**Comment by DEGoodmanWilson** [comment]
This is only going to get worse, thanks for bringing this forward.

**Comment by DEGoodmanWilson** [comment]
Wow, I'm getting behind. This was fixed in v4.0. Sorry!
