### ISSUE TITLE
slack-client just released v2

### ISSUE THREAD

**Issue by hbrls** [slackhq/hubot-slack#276]
Do you have any plan to keep up?

**Comment by l12s** [comment]
I've added an issue in `slack-client` to track the work involved on our side: https://github.com/slackhq/node-slack-client/issues/141

Loosely, I'd like to have the `>= 2.0.x` release of `slack-client` in use for at least 2-4 weeks before I talk to projects that depended on the old client. That's to make sure that any bugs / problems in the new version (especially reconnection logic handling) get fixed before it gets locked in as a dependency.

**Comment by hbrls** [comment]
Can I have a test of your branch too? I'm bugged by the auto-reconnect issue. Hope that v2 will solve it.

**Comment by l12s** [comment]
Sure - it's probably going to be at least a couple weeks until I start on it though, with that timeline depending on how many bugs on the 2.0.x version come in and getting input from the lead maintainers on hubot.

I'll update this comment once I have one in motion though.

**Comment by ZebraFlesh** [comment]
This upgrade is important for Windows users. Windows users can't move past node 0.10 until the new version of slack-client is integrated. (See #199)

**Comment by lisfox1** [comment]
Any more news on upgrade to slack-client v2?

**Comment by DEGoodmanWilson** [comment]
Check it out! https://github.com/slackhq/hubot-slack/pull/309 Please have a look at the branch backing this PR, and comment there on whether it is working for you or not.
