### ISSUE TITLE
Upgrade slack-client to ^2.0.2

### ISSUE THREAD

**Issue by ZebraFlesh** [slackhq/hubot-slack#278]
The slack-client package has finally fixed the broken `ws` dependency so theoretically hubot-slack can now be installed on node >= 0.11.  This is a major version change and will likely require changes to this package.  (Or, I'd really like to run my hubot install on a not-ancient version of node.)

**Comment by hbrls** [comment]
#276

And I'm using it on node 4 because I did not know it could not. What's the problem with >= 0.11?

**Comment by ZebraFlesh** [comment]
I just cross checked platforms and this issue appears to be specific to Windows. Further details are in #199 . But the issue you referenced is earlier, so I'll close this one in favor of that one. Thanks!
