### ISSUE TITLE
Hubot/slack adapter times out?

### ISSUE THREAD

**Issue by ezgoodnight** [slackhq/hubot-slack#282]
After about a day's worth of connected uptime, the hubot seems to crash. Sort of.

It ran flawlessly for days on end with the Slack adapter when I was running Ubuntu 14.04 on an older machine. Now on a newer machine running Linux Mint 17.3 Rosa, after about 12 to 24 hours it seems to stop working.

I'm using the same upstart script, but my node/hubot/adapter installations are all fresh ones.

I still get a green light for the bot in Slack, but he doesn't respond to commands, even ones that his own server `curl`s to him.

Thoughts? The logs didn't seem to include anything useful. Is this a hubot problem or an adapter problem?

I got a similar problem with a cloud VM and the twitter adapter, but my only solution was to write a script to restart the server with `cron`.

**Comment by ezgoodnight** [comment]
I couldn't find other discussion about this earlier, now I have. :/

https://github.com/slackhq/hubot-slack/issues/203

Here's the solution that I'm trying, which is replacing slack.coffee with this updated file:

https://github.com/eriklindebratt/hubot-slack/blob/master/src/slack.coffee

**Comment by ezgoodnight** [comment]
This is the reply that got me this info: https://github.com/github/hubot/issues/1013#issuecomment-131013071

**Comment by ezgoodnight** [comment]
About a day of using the updated slack.coffee files and I have had no problems.

**Comment by DEGoodmanWilson** [comment]
This should be fixed in https://github.com/slackhq/hubot-slack/pull/309
