### ISSUE TITLE
hubot not working with systemd

### ISSUE THREAD

**Issue by marceloslacerda** [slackhq/hubot-slack#287]
I'm copying this bug here because I don't know whether this bug belongs to hubot or hubot-slack https://github.com/github/hubot/issues/1152

I have tried to configure hubot according to the example[1], but the service does not connect.

Here is what happens when I run hubot manually:

https://gist.github.com/marceloslacerda/13b8f27621b8939b694f

Notice how the "Connecting..." info is displayed correctly.
So I tried to configure hubot for systemd. This is the service file:

https://gist.github.com/marceloslacerda/cf2e24df1aad1af95acf

And the log after running # systemctl daemon-reload; systemctl start hubot

https://gist.github.com/marceloslacerda/ef1ed465a18d647011b8

Notice how the "Connecting..." message does not appear and how hubot-slack throws an error, but I don't know what is it about.

What am I doing wrong?

**Comment by praseodym** [comment]
Apparently you're not providing the correct service token. The setup should work fine, we're running it using a similar service file.

**Comment by marceloslacerda** [comment]
As a workaroud we were used a bash script as a bootstrap script for hubot and put that in our systemd service file.

https://gist.github.com/marceloslacerda/fab1225f28a28a4a27aebf41b6916db6

**Comment by DEGoodmanWilson** [comment]
Closing as resolved.
