### ISSUE TITLE
removeFormatting does not work for subteams

### ISSUE THREAD

**Issue by jabbink** [slackhq/hubot-slack#288]
When trying to parse an unformatted message, subteams get replaced by `undefined`

    text: 'undefined hello',
    rawText: '<!subteam^xxx|@yyy> hello',

https://github.com/slackhq/hubot-slack/blob/master/src/slack.coffee#L174

**Comment by DEGoodmanWilson** [comment]
No doubt related to, and will be fixed with #114 This is pretty high-priority stuff, and it's not _strictly speaking_ a duplicate, but I am going to mark it as a duplicate since fixing this and fixing #114 are almost assuredly the same thing.

**Comment by DEGoodmanWilson** [comment]
Oops, didn't mean to close the issue!

**Comment by DEGoodmanWilson** [comment]
Closing this as fixed in 4.0. Please reopen if I am mistaken!

**Comment by ndaversa** [comment]
@DEGoodmanWilson This still seems broken to me in v4.2.1

https://github.com/slackhq/hubot-slack/pull/366 does seem to resolve the issue though
