### ISSUE TITLE
Problem with news.coffee. Didn't fetch latest news based on my keywords.

### ISSUE THREAD

**Issue by thinhduckhoi** [slackhq/hubot-slack#289]
Hi everyone, 
So i just found out about this useful script and used it on my Slack channel.
The point is sometimes it works and sometimes it doesn't.
For example, with the topic like; smartphone, technology it always give me a long list of latest news.
But when i use keywords like: aws, azure, it didn't reply anything.
So could someone tell me how to fix this problem, please?

**Comment by jabbink** [comment]
I assume you're talking about [this](https://github.com/github/hubot-scripts/blob/master/src/scripts/news.coffee)? Because then you should make an issue there, and not on this repository (which is about the Slack connector for hubot).

**Comment by DEGoodmanWilson** [comment]
Closing as off topic
