### ISSUE TITLE
files.upload method

### ISSUE THREAD

**Issue by kengz** [slackhq/hubot-slack#290]
As detailed in Slack RTC method [files.upload](https://api.slack.com/methods/files.upload), is this currently supported (if so, how to use)?

Also related to RTC is this event emitted when file is uploaded to slack, [file_created](https://api.slack.com/events/file_created). 

This is for Slack bot to do computer vision on image files from users.

**Comment by DEGoodmanWilson** [comment]
Hello? Just to clarify, is this a question about _using_ `hubot-slack`, or are you reporting that something is broken or missing?

**Comment by kengz** [comment]
Hi. It's a question about a method seems to be *missing* from `hubot-slack`, or equivalently a feature request, if hasn't already been implemented.

**Comment by DEGoodmanWilson** [comment]
Understood. This method is exposed in the latest development branch—indeed, all of the web api methods are available through `@robot.client`. Have a look at the development branch here: https://github.com/slackhq/hubot-slack/pull/309

**Comment by DEGoodmanWilson** [comment]
Closing this as fixed in 4.0. Please reopen if I am mistaken!
