### ISSUE TITLE
Hubot to leave slack channel?

### ISSUE THREAD

**Issue by lilnate22** [slackhq/hubot-slack#298]
Anyway to programmatically have hubot leave a slack channel?  
right now, if the bot is invited, you cannot un-invite him

**Comment by anupdhml** [comment]
@lilnate22 not possible right now -- slack api forbids it for bot users. More discussion here: https://github.com/slackhq/hubot-slack/issues/202#issuecomment-149719884

**Comment by lilnate22** [comment]
This seems a bit of undersight that there is no programatic way for a bot user to leave a channel.

what this entails is for slack users with bots (like say hubot), that other users might invite, is now stuck in channel until an admin comes by

**Comment by ChristopherJoonMiller** [comment]
👍  need a way to kick the bot without being an admin.

**Comment by DEGoodmanWilson** [comment]
This is a feature request for the Slack API generally, rather than `hubot-slack` specifically, so closing as off-topic.

**Comment by lilnate22** [comment]
@DEGoodmanWilson  and where does one to a FR for slack?

**Comment by DEGoodmanWilson** [comment]
You can email feedback@slack.com, or just type `/feedback [your feedback here]` into any Slack channel.
