### ISSUE TITLE
What does hubot know of the channels in Slack?

### ISSUE THREAD

**Issue by alfred** [slackhq/hubot-slack#302]
I am writing a hubot script that is reliant on hubot being able to give me a list of users in a specific Slack channel.

Does hubot have any way of looking up users in a channel?

I know I can get *all* users in Slack, but not sure if there is a `getUsersByChannelId` style function on the robot?

I spent the greater part of the day reading through other hubot-scripts and googling, so I must have missed something.

**Comment by ramananbalakrishnan** [comment]
An instance of [`slack-client`](https://github.com/slackhq/node-slack-sdk) is available as `robot.adapter.client` . 

You should be able to use this for your channels. Once you retrieve a `channel` object via `getChannelGroupOrDMByName` (like in https://github.com/slackhq/hubot-slack/blob/c0775f4f4a2e7718d3f0e1edb3a818b945485e41/src/slack.coffee#L217) , you can look at the members in that channel by looking at the `members` field in the `channel` object.
i.e. 
```coffee
channel = getChannelGroupOrDMByName 'general'
channel.members
```

Additional functions from `slack-client` should also be available. However, I think that the version of `slack-client` here is `~1.5`  , whereas the latest release as of this comment is `3.3.0`.

**Comment by DEGoodmanWilson** [comment]
Closing as solved.

**Comment by jiefugong** [comment]
@ramananbalakrishnan sorry to revisit this old issue -- i have accessed an instance of my slack-client as `robot.adapter.client` but it seems there is no access to `getChannelGroupOrDMByName`, I have to manually traverse the fields of the object. Do you have a specific example on how to use this?

**Comment by ramananbalakrishnan** [comment]
@jiefugong , it took me a while to identify the reasons for this.

- looks like `hubot-slack` now requires [`@slack/client : "^3.4.0"`](https://github.com/slackapi/node-slack-sdk/tree/3.4.0)
- a number of things changed when `@slack/client` went to `2.x` and beyond. you might want to refer to this issue https://github.com/slackapi/node-slack-sdk/issues/141 there .
- you should be able to use the old helper functions following the instructions here https://github.com/slackapi/node-slack-sdk/issues/141#issuecomment-191015275

My guess is that you can use the `RtmClient` inside `robot.adapter.client`, try `robot.adapter.client.rtm.dataStore. getChannelGroupOrDMByName()`
