### ISSUE TITLE
Ability to call hubot

### ISSUE THREAD

**Issue by rajatguptarg** [slackhq/hubot-slack#303]
Hey,

Actually this is not a issue. This is feature request. As we know Slack has feature to call team members. It will be nice to have the feature to call hubot and we can implement listeners to parse the audio.

Its just a idea. Lets see, what people say?

**Comment by DEGoodmanWilson** [comment]
Right now, we have no API methods exposed to accomplish any of this, I'm sorry to say. We can revisit if we expose any endpoints for making calls!
