### ISSUE TITLE
Adapter doesn't die when there's no connection

### ISSUE THREAD

**Issue by Place1** [slackhq/hubot-slack#311]
If you start the bot without internet connection the slack-client will emit an error 'ENOTFOUND' but the adapter currently doesn't handle it.

Currently the adapter will just log 'ERROR undefined' but it will not exit nor try to reconnect.

It'd be great if the adapter followed the HUBOT_SLACK_EXIT_ON_DISCONNECT environment option flag in this condition. If the flag is true then the adapter should exit otherwise should try and reconnect.

If others thing this is a good addition i'm happy to make a PR for it.

**Comment by DEGoodmanWilson** [comment]
Interesting, and worth looking into. Thanks for reporting it—I'd love a PR of course, but I'd like to wait until we have merged in the migration to `node-slack-sdk` v3.x

**Comment by Place1** [comment]
sounds great. maybe let me know when those changes are rolled in and i'll take another look :D

**Comment by DEGoodmanWilson** [comment]
@Place1 Have a look here, would love more 👀 on this: https://github.com/slackhq/hubot-slack/pull/309

**Comment by DEGoodmanWilson** [comment]
Closing this as fixed in 4.0. Please reopen if I am mistaken!
