### ISSUE TITLE
Hubot not replying on slack

### ISSUE THREAD

**Issue by sumanthvm** [slackhq/hubot-slack#312]
Hubot works fine on shell, but only doesn't return back to shell automatically after receiving any message..

currently I am trying to integrate hubot with slack following instructions provided as in https://github.com/slackhq/hubot-slack

but my hubot doesn't respond back to slack.

== Debug Details
```
[Thu Jun 30 2016 10:00:00 GMT+0000 (UTC)] INFO Logged in as ibot of IBMTEST, but not yet connected
[Thu Jun 30 2016 10:00:02 GMT+0000 (UTC)] INFO Slack client now connected
[Thu Jun 30 2016 10:00:02 GMT+0000 (UTC)] DEBUG Loading scripts from /home/hubot/hubot/scripts
[Thu Jun 30 2016 10:00:02 GMT+0000 (UTC)] DEBUG Parsing help for /home/hubot/hubot/scripts/example.coffee
[Thu Jun 30 2016 10:00:02 GMT+0000 (UTC)] DEBUG Loading scripts from /home/hubot/hubot/src/scripts
[Thu Jun 30 2016 10:00:02 GMT+0000 (UTC)] DEBUG Loading hubot-scripts from /home/hubot/hubot/node_modules/hubot-scripts/src/scripts
[Thu Jun 30 2016 10:00:02 GMT+0000 (UTC)] WARNING Loading scripts from hubot-scripts.json is deprecated and will be removed in 3.0 (https://github.com/github/hubot-scripts/issues/1113) in favor of packages for each script.

Your hubot-scripts.json is empty, so you just need to remove it.
[Thu Jun 30 2016 10:00:02 GMT+0000 (UTC)] DEBUG Loading external-scripts from npm packages
[Thu Jun 30 2016 10:00:02 GMT+0000 (UTC)] DEBUG Parsing help for /home/hubot/hubot/node_modules/hubot-diagnostics/src/diagnostics.coffee
[Thu Jun 30 2016 10:00:02 GMT+0000 (UTC)] DEBUG Parsing help for /home/hubot/hubot/node_modules/hubot-help/src/help.coffee
[Thu Jun 30 2016 10:00:02 GMT+0000 (UTC)] ERROR hubot-heroku-alive included, but missing HUBOT_HEROKU_KEEPALIVE_URL. heroku config:set HUBOT_HEROKU_KEEPALIVE_URL=$(heroku apps:info -s  | grep web-url | cut -d= -f2)
[Thu Jun 30 2016 10:00:02 GMT+0000 (UTC)] DEBUG Parsing help for /home/hubot/hubot/node_modules/hubot-heroku-keepalive/src/heroku-keepalive.coffee
[Thu Jun 30 2016 10:00:02 GMT+0000 (UTC)] DEBUG Parsing help for /home/hubot/hubot/node_modules/hubot-google-images/src/google-images.coffee
[Thu Jun 30 2016 10:00:02 GMT+0000 (UTC)] DEBUG Parsing help for /home/hubot/hubot/node_modules/hubot-google-translate/src/google-translate.coffee
[Thu Jun 30 2016 10:00:02 GMT+0000 (UTC)] DEBUG Parsing help for /home/hubot/hubot/node_modules/hubot-pugme/src/pugme.coffee
[Thu Jun 30 2016 10:00:02 GMT+0000 (UTC)] DEBUG Parsing help for /home/hubot/hubot/node_modules/hubot-maps/src/maps.coffee
[Thu Jun 30 2016 10:00:03 GMT+0000 (UTC)] INFO hubot-redis-brain: Using default redis on localhost:6379
[Thu Jun 30 2016 10:00:03 GMT+0000 (UTC)] DEBUG Parsing help for /home/hubot/hubot/node_modules/hubot-redis-brain/src/redis-brain.coffee
[Thu Jun 30 2016 10:00:03 GMT+0000 (UTC)] DEBUG Parsing help for /home/hubot/hubot/node_modules/hubot-rules/src/rules.coffee
[Thu Jun 30 2016 10:00:03 GMT+0000 (UTC)] DEBUG Parsing help for /home/hubot/hubot/node_modules/hubot-shipit/src/shipit.coffee
[Thu Jun 30 2016 10:00:18 
GMT+0000 (UTC)] DEBUG Received message: '@ibot: help' in channel: sumanthvm, from: sumanthvm
[Thu Jun 30 2016 10:00:18 GMT+0000 (UTC)] DEBUG No listeners executed; falling back to catch-all
```

**Comment by DEGoodmanWilson** [comment]
It looks like you haven't implemented any Hubot scripts? I think by default, you should be able to DM your bot with "ping" and get "pong" back as a test, does that work?

**Comment by sumanthvm** [comment]
Greetings,

No even for ping it is not replying back.


export HUBOT_SLACK_TOKEN=########################################
export HUBOT_LOG_LEVEL="debug"
./bin/hubot --adapter "slack" --name "ibot" --alias !






 
 

11:44:48 AM


Sumanth V
Madyalkar

Senior Advisory Product Services
GBS - DST


Phone: 91-080-40664370 x000 | Mobile: 91-988-0610807
E-mail: sumanthvm@in.ibm.com
Chat: sumanthvm@in.ibm.com 


Outer Ring Road, MTP
Bangalore, KA 560045
India

**Comment by DEGoodmanWilson** [comment]
Can you paste in (preferably neatly formatted) logs showing me that Hubot did indeed receive the ping message, but failed to respond?

Have you tried enabling any of the example scripts in the `scripts` folder?

**Comment by sumanthvm** [comment]
[Wed Jul 27 2016 10:22:16 GMT+0530 (IST)] DEBUG Loading adapter slack
[Wed Jul 27 2016 10:22:17 GMT+0530 (IST)] INFO Connecting...
[Wed Jul 27 2016 10:22:17 GMT+0530 (IST)] ERROR Error: listen EADDRINUSE 0.0.0.0:8080
  at Object.exports._errnoException (util.js:870:11)
  at exports._exceptionWithHostPort (util.js:893:20)
  at Server._listen2 (net.js:1234:14)
  at listen (net.js:1270:10)
  at net.js:1379:9
  at nextTickCallbackWith3Args (node.js:453:9)
  at process._tickCallback (node.js:359:17)

[Wed Jul 27 2016 10:22:19 GMT+0530 (IST)] INFO Logged in as ibot of IBMTEST, but not yet connected
[Wed Jul 27 2016 10:22:21 GMT+0530 (IST)] INFO Slack client now connected
[Wed Jul 27 2016 10:22:21 GMT+0530 (IST)] DEBUG Loading scripts from /home/hubot/ibot/scripts
[Wed Jul 27 2016 10:22:21 GMT+0530 (IST)] DEBUG Parsing help for /home/hubot/ibot/scripts/example.coffee
[Wed Jul 27 2016 10:22:21 GMT+0530 (IST)] DEBUG Loading scripts from /home/hubot/ibot/src/scripts
[Wed Jul 27 2016 10:22:21 GMT+0530 (IST)] DEBUG Loading hubot-scripts from /home/hubot/ibot/node_modules/hubot-scripts/src/scripts
[Wed Jul 27 2016 10:22:21 GMT+0530 (IST)] WARNING Loading scripts from hubot-scripts.json is deprecated and will be removed in 3.0 (https://github.com/github/hubot-scripts/issues/1113) in favor of packages for each script.

Your hubot-scripts.json is empty, so you just need to remove it.
[Wed Jul 27 2016 10:22:21 GMT+0530 (IST)] DEBUG Loading external-scripts from npm packages
[Wed Jul 27 2016 10:22:21 GMT+0530 (IST)] DEBUG Parsing help for /home/hubot/ibot/node_modules/hubot-diagnostics/src/diagnostics.coffee
[Wed Jul 27 2016 10:22:21 GMT+0530 (IST)] DEBUG Parsing help for /home/hubot/ibot/node_modules/hubot-help/src/help.coffee
[Wed Jul 27 2016 10:22:21 GMT+0530 (IST)] ERROR hubot-heroku-alive included, but missing HUBOT_HEROKU_KEEPALIVE_URL. `heroku config:set HUBOT_HEROKU_KEEPALIVE_URL=$(heroku apps:info -s  | grep web-url | cut -d= -f2)`
[Wed Jul 27 2016 10:22:21 GMT+0530 (IST)] DEBUG Parsing help for /home/hubot/ibot/node_modules/hubot-heroku-keepalive/src/heroku-keepalive.coffee
[Wed Jul 27 2016 10:22:21 GMT+0530 (IST)] DEBUG Parsing help for /home/hubot/ibot/node_modules/hubot-google-images/src/google-images.coffee
[Wed Jul 27 2016 10:22:21 GMT+0530 (IST)] DEBUG Parsing help for /home/hubot/ibot/node_modules/hubot-google-translate/src/google-translate.coffee
[Wed Jul 27 2016 10:22:21 GMT+0530 (IST)] DEBUG Parsing help for /home/hubot/ibot/node_modules/hubot-pugme/src/pugme.coffee
[Wed Jul 27 2016 10:22:21 GMT+0530 (IST)] DEBUG Parsing help for /home/hubot/ibot/node_modules/hubot-maps/src/maps.coffee
[Wed Jul 27 2016 10:22:21 GMT+0530 (IST)] INFO hubot-redis-brain: Using default redis on localhost:6379
[Wed Jul 27 2016 10:22:21 GMT+0530 (IST)] DEBUG Parsing help for /home/hubot/ibot/node_modules/hubot-redis-brain/src/redis-brain.coffee
[Wed Jul 27 2016 10:22:21 GMT+0530 (IST)] DEBUG Parsing help for /home/hubot/ibot/node_modules/hubot-rules/src/rules.coffee
[Wed Jul 27 2016 10:22:21 GMT+0530 (IST)] DEBUG Parsing help for /home/hubot/ibot/node_modules/hubot-shipit/src/shipit.coffee
[Wed Jul 27 2016 10:22:21 GMT+0530 (IST)] DEBUG hubot-redis-brain: Successfully connected to Redis
[Wed Jul 27 2016 10:22:21 GMT+0530 (IST)] INFO hubot-redis-brain: Data for hubot brain retrieved from Redis
[Wed Jul 27 2016 10:38:43 GMT+0530 (IST)] DEBUG Received message: 'ping @ibot' in channel: sumanthvm, from: sumanthvm
[Wed Jul 27 2016 10:38:43 GMT+0530 (IST)] DEBUG No listeners executed; falling back to catch-all
[Wed Jul 27 2016 10:39:04 GMT+0530 (IST)] DEBUG Received message: '@ibot:  ping' in channel: sumanthvm, from: sumanthvm
[Wed Jul 27 2016 10:39:04 GMT+0530 (IST)] DEBUG No listeners executed; falling back to catch-all

**Comment by sumanthvm** [comment]
Thanks for your help, I got the issue resolved by the following steps:

# node -v
v4.4.5
# npm -v
3.10.5
npm install -g css-what
npm install -g css-select
npm install -g minimatch
npm install -g npm
npm install -g yo generator-hubot

**Comment by nildenrey** [comment]
Hi,
I have the same issue.  but this time on mattermost. hubot is replying to my terminal but when I used to call hubot in mattermost there is no any response.  maybe I need to set up variables to connect hubot on my mattermost but my problem is where to find those variables. please help...

here's the variable that need to set up?

![variable](https://user-images.githubusercontent.com/37136917/38973622-5fbdbbfc-43d9-11e8-9a96-f5aafbe6cc44.PNG)
