### ISSUE TITLE
slack-client depcrecated

### ISSUE THREAD

**Issue by feelinsly** [slackhq/hubot-slack#313]
When I install the package, it says: npm WARN deprecated slack-client@1.4.1: Use @slack/client instead, this package is no longer maintained

**Comment by pixelrebel** [comment]
I have a similar issue.  Trying to get hubot-slack to work behind a proxy.  I can see hubot-slack is passing `proxyUrl` to slack-client, but only the new client actually has support for this.

https://github.com/slackhq/hubot-slack/blob/master/src/slack.coffee#L25-L33

Not sure how to move forward until hubot-slack starts using the new client.

**Comment by natdempk** [comment]
It looks like the change to use `@slack/client` is included as part of https://github.com/slackhq/hubot-slack/pull/309

**Comment by thebeefcake** [comment]
I'm seeing this also

**Comment by DEGoodmanWilson** [comment]
@natdempk has it right: We are actively working on this in #309. Closing for now.
