### ISSUE TITLE
Error while install

### ISSUE THREAD

**Issue by sjkeerthi** [slackhq/hubot-slack#317]
yo hubot
                     _____________________________  
                    /                             \ 
   //\              |      Extracting input for    |
  ////\    _____    |   self-replication process   |
 //////\  /_____\   \                             / 
 ======= |[^_/\_]|   /----------------------------  
  |   | _|___@@__|__                                
  +===+/  ///     \_\                               
   | |_\ /// HUBOT/\\                             
   |___/\//      /  \\                            
         \      /   +---+                            
          \____/    |   |                            
           | //|    +===+                            
            \//      |xx|                            

? Owner opsbot
? Bot name myhubot
? Description A simple helpful robot for your Company
? Bot adapter campfire
/usr/local/lib/node_modules/generator-hubot/node_modules/mkdirp/index.js:90
                    throw err0;
                    ^

Error: EACCES: permission denied, mkdir '/root/myhubot/bin'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:842:18)
    at Function.sync (/usr/local/lib/node_modules/generator-hubot/node_modules/mkdirp/index.js:71:13)
    at yeoman.generators.Base.extend.writing.app (/usr/local/lib/node_modules/generator-hubot/generators/app/index.js:246:12)
    at /usr/local/lib/node_modules/generator-hubot/node_modules/yeoman-generator/lib/base.js:395:14
    at processImmediate [as _immediateCallback] (timers.js:383:17)

# id
uid=0(root) gid=0(root) groups=0(root)

**Comment by sjkeerthi** [comment]
This throw error when I run as root

**Comment by DEGoodmanWilson** [comment]
Howdy! This looks like an error with `generator-hubot` (https://github.com/github/generator-hubot) , and not `hubby-slack`. Closing as off topic.
