### ISSUE TITLE
`bot_message` still exists

### ISSUE THREAD

**Issue by fcoelho** [slackhq/hubot-slack#323]
#### Description
Commit https://github.com/slackhq/hubot-slack/commit/4f3f430b54f76f90c53e355b93b5fc401b6c3d57 removed support for bot messages, but it seems messages with the `bot_message` subtype still exist and are in use. Any time a bot message is received by my hubot instance [this else](https://github.com/slackhq/hubot-slack/blob/master/src/bot.coffee#L148-L150) is executed and we get a traceback:

```
ERROR TypeError: Cannot read property 'room' of undefined
  at CatchAllMessage.Message (/usr/src/app/node_modules/hubot/src/message.coffee:6:5, <js>:10:28)
  at new CatchAllMessage (/usr/src/app/node_modules/hubot/src/message.coffee:63:19, <js>:84:45)
  at SlackBot.message (/usr/src/app/node_modules/hubot-slack/src/bot.coffee:150:9, <js>:196:31)
  ...
```

this causes the bot to also disconnect for a short period of time.

It seems like the fix is basically reverting the change, but if bot messages are really going away, this might be a no-op. I couldn't find any info on that on the api changelog though, and the [`bot_message` event page](https://api.slack.com/events/message/bot_message) also doesn't say anything about it. If this isn't actually going away, I can put up with a quick pr+test to fix it

#### Reproducible in:
hubot-slack version: 4.0.0

#### Steps to reproduce:

1. Install slack-hubot==4.0.0
2. Receive a bot message

### Expected result:
Business as usual

### Actual result:
Traceback and disconnect

**Comment by spacediver** [comment]
I observe this too. If Slack API **in fact** continues to send it, we should support that, not crash on that?

**Comment by DEGoodmanWilson** [comment]
Thanks for the heads-up, y'all, looking into this today!
