### ISSUE TITLE
context.response.message.room value changed from 3.4.2 to 4.0

### ISSUE THREAD

**Issue by twellspring** [slackhq/hubot-slack#328]
#### Description
context.response.message.room used to be the name of the room and/or the username if a user sent a Direct Message.  With the 4.0 version the value is now an alphanumeric string.

What is the new alphanumeric value in the room field?
Is there a way to get the room name ( rather than the alphanumeric string) out of some other location in the context object or something else available in middleware?
Is there a way to lookup the room name from this alphanumeric string?
Has the room changed in any other locations?

#### Reproducible in:
hubot-slack version: 4.0.0, 4.0.1
OS version(s): Ubuntu 14.04
Device(s):

#### Steps to reproduce:

1. In a middelware, log the value of context.response.message.room
2. upgrade to 4.0.1
3. log the values of context.response.message.room

### Expected result:
> e.g. What you expected to happen

when sending DM, context.response.mesage.room = context.response.message.user.name
when sending from a room  context.response.message.room = the room's name 

### Actual result:
> e.g. What actually happened

context.response.message.room = a  numeric string ( example: "D0SFNA5V0" ) 

### Attachments:
> e.g. Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by ArcticSnowman** [comment]
I would concur with this issue.   A number of hubot scripts started reporting the slack channel ID (that alpha-numberic string) rather than the name of the channel.  This cause settings and stored data to be lost for the channel as the name had changed.   This is total broken and makes 4.0+ not backwards compatible with 3.x

**Comment by twellspring** [comment]
Yes, learned about that non-backwards compatibility when trying to upgrade to fix slack-disconnect issue per #203

**Comment by bcoia** [comment]
I'm currently using this workaround to get the room name, using the client to retrieve the room name by ID:

`roomname = robot.adapter.client.rtm.dataStore.getChannelGroupOrDMById res.message.room`

I agree that it should return the room name instead of the room ID, for compatibility with 3.x.

**Comment by lecoueyl** [comment]
@twellspring Exactly the same here. I had to rollback to 3.x because I have to many script using the room name (and not the id) to send a message.
This is not working anymore: `robot.messageRoom roomName, message`

**Comment by lecoueyl** [comment]
@bcoia 

This return the channel information from the channel's id (`C0273OPPE`) like this

```
{ history:
   [ { type: 'message',
       user: 'UXXXXXXXX',
       text: 'test',
       ts: '1469501927.000004' } ],
  _typing: {},
  unreadCount: 1,
  lastRead: '0000000000.000000',
  _maxTs: '1469501927.000004',
  _properties:
   { id: 0,
     name: 0,
     is_channel: 0,
     created: 0,
     creator: 0,
     is_archived: 0,
     is_general: 0,
     has_pins: 0,
     is_member: 0,
     last_read: 0,
     latest: 0,
     unread_count: 0,
     unread_count_display: 0,
     members: 0,
     topic: 0,
     purpose: 0 },
  _modelName: 'Channel',
  id: 'C0273OPPE',
  name: 'general',
  is_channel: true,
  created: 1417484920,
  creator: 'UXXXXXXXX',
  is_archived: false,
  is_general: false,
  has_pins: false,
  is_member: true,
  last_read: '1469501927.000004',
  latest:
   { type: 'message',
     user: 'UXXXXXXXX',
     text: 'test',
     ts: '1469501927.000004' },
  unread_count: 0,
  unread_count_display: 0,
  members: [ 'UXXXXXXXX', 'UXXXXXXXX', 'UXXXXXXXX', 'UXXXXXXXX', 'UXXXXXXXX' ],
  topic: { value: '', creator: '', last_set: 0 },
  purpose: { value: '', creator: '', last_set: 0 } }
```

This is not helping because you still need to know the channel's id. Before in `3.x` you could interact with a room using it's name without knowing the channel's

There is not default method like `getChannelGroupOrDMByName` to retrieve the channel's id from the room name. The only thing you can do is to list the channel's and get the channel id from the name

**Comment by ArcticSnowman** [comment]
In bot.coffee, the user.room is set to channel.id 

      message: (message) =>
        {text, user, channel, subtype, topic, bot} = message
    
        subtype = subtype || 'message'
    
       # Hubot expects this format for TextMessage Listener
        user = bot if bot
        user = user if user
        user = {} if !user && !bot
        user.room = channel.id

In the previous version slack.coffee set it to channel.name

      message: (msg) =>
        # Ignore our own messages
        return if msg.user == @self.id
    
        channel = @client.getChannelGroupOrDMByID msg.channel if msg.channel
    
        if msg.hidden or (not msg.text and not msg.attachments) or msg.subtype is 'bot_message' or not msg.user or not channel
          # use a raw message, so scripts that care can still see these things
    
          if msg.user
            user = @robot.brain.userForId msg.user
          else
            # We need to fake a user because, at the very least, CatchAllMessage
            # expects it to be there.
            user = {}
            user.name = msg.username if msg.username?
          user.room = channel.name if channel

**Comment by DEGoodmanWilson** [comment]
Howdy y'all. I'm going to argue that you should _not_ be keying anything on channel names, because channel names are volatile (yes, event "#general"), where channel id's are not. This breaking change is quite deliberate, as the previous behavior is now to us clearly a mistake. If you need the room name, @bcoia has the right idea, you can extract it from the Slack client's cache with `robot.adapter.client.rtm.dataStore.getChannelGroupOrDMById()`

**Comment by p00j4** [comment]
query: 
isn't there any direct way to get channel name instead of channel id?
```msg.message.room``` returns channel id

**Comment by aoberoi** [comment]
@p00j4 you can use slack's web API method [`conversations.list`](https://api.slack.com/methods/conversations.list) to retrieve a list of all conversations and then iterate over them to search for the ID. fortunately, there's already a WebClient object available in the adapter, so the code should look something like:

```javascript
let channelName = 'mychannel';
robot.adapter.client.web.conversations.list().then(results => {
  let channel = results.channels.find(conversation => (conversation.name && conversation.name == channelName));
  if (channel) {
    console.log(`the channel named ${channelName} has the ID: ${channel.id}.`);
  } else {
    console.log(`the channel named ${channelName} was not found.`);
  }
});
```

you might want to extend this by creating a helper function for your script. also, if you are working on a large workspace, you should take advantage of the [pagination arguments](https://api.slack.com/docs/pagination) to make sure your request does not timeout.
