### ISSUE TITLE
4.0.1 Formatting removes profile picture/bot name

### ISSUE THREAD

**Issue by SecurityInsanity** [slackhq/hubot-slack#329]
* [X] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

#### Description
After upgrading to hubot 4.0.1 I've noticed when sending "special" formatted links, or using items such as the "help" command the bot seems to lose it's profile picture/name.

This is an example of a command without any special formatting:
![Flipping a Coin](https://cloud.githubusercontent.com/assets/7262714/17126953/0fd1eb98-52bf-11e6-87d7-5258ce9d0e13.png) The script for which is:
```coffee
thecoin = ["heads", "tails"]

module.exports = (robot) ->
  robot.respond /(throw|flip|toss) a coin/i, (msg) ->
    msg.reply msg.random thecoin
```

Notice how the profile picture + bot name of "gwiz-bot" appear.

Next I try the help command:
![Help command](https://cloud.githubusercontent.com/assets/7262714/17127084/1471c208-52c0-11e6-8371-48c2e4f33c3e.png)

Note how it's switched to a blank profile picture, and just "bot".

This also happens when using the special formatted text that now works. I.E. the script below causes him to go profile-pictureless:
```coffee
module.exports = (robot) ->
  robot.respond /(throw|flip|toss) a coin two/i, (msg) ->
    msg.reply '<https://google.com|google>'
```

#### Reproducible in:
Hubot-Slack version: 4.0.1
Server OS Version: Ubuntu 14.04 LTS
Client OS Versions: Ubuntu 16.04.1 LTS, Android 6.0.1
Client Slack Versions: 2.1.0 64-bit Direct Download, 2.14.0-C-20002406

#### Steps to reproduce:

1. Install hubot slack v4.0.1 as outlined in the docs.
2. Try running the help command.
3. Notice the bots profile picture doesn't appear.

### Expected result:
To see the bots profile picture/name

### Actual result:
I see "Bot" with no profile picture.

### Extra Notes:

I feel like there's probably a configuration option I can pass into hubot to set this picture/name. However I've set the hubot name as outlined in the hubot docs, and that doesn't appear nor do I see any configuration options for a profile picture.

**Comment by ArcticSnowman** [comment]
See #325 for the cause.

**Comment by SecurityInsanity** [comment]
Yep. I was able to specify those values, and get the bot to respond right (for the custom commands at least). Since the help command isn't too big of a deal, and there's other issues. I'm going to close this.

**Comment by DEGoodmanWilson** [comment]
@SecurityInsanity Just to verify, were you able to resolve by adding `as_user:true`?

**Comment by SecurityInsanity** [comment]
@DEGoodmanWilson No it seemed like as_user wasn't working? At least that's the general tone I got. So for specially formatted messages _for now_ I've started manually specifying the name/url based on ENV Vars.

**Comment by DEGoodmanWilson** [comment]
Gotcha, just wanted to clarify! Thanks!
