### ISSUE TITLE
Questions: How to access Web API client from within a Hubot script

### ISSUE THREAD

**Issue by lukaspustina** [slackhq/hubot-slack#334]
* [x] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

I'm trying to upload a file from my Hubot instance. Following the Slack API, I understood that I have to use the Web API call `files.upload`. Issue #290 states that there should be a way to access the Web Client via `@robot.client`. Unfortunately, there's no key `client` in `robot`. I also tried to access `@web` via `robot.adapter.client`, but there is no such key `web` in it.

It would be very helpful, if you could give a snippet on how to access the web client from a robot script.

#### Reproducible in:
Hubot 2.19.0, Hubot-Slack 4.0.1

#### Steps to reproduce:

From a handler in a robot script

1. `console.log robot.client` is undefined
2. `console.log robot.adapter.client.rtm` is undefined

**Comment by DEGoodmanWilson** [comment]
Have you tried `robot.adapter.web`/`robot.adapter.rtm`? I _think_ that's the right way to get the web client and RTM client.

**Comment by lukaspustina** [comment]
Hello @DEGoodmanWilson, sorry for coming back to you so late.

Yes, I did try that w/o any luck:
- `console.log robot.adapter.rtm` is `undefined`
- `console.log robot.adapter.web` is `undefined`

Any other ideas?

**Comment by DEGoodmanWilson** [comment]
Sorry! It's `robot.adapter.client.[rtm|client]`

**Comment by sajeeshgit** [comment]
Looks like web is  not present in latest version in  robot.adapter.client . Could you tell how to gets the web.reactions from the robot object ?

**Comment by aoberoi** [comment]
hi @sajeeshgit, there's a section in the documentation that answers this question: https://slackapi.github.io/hubot-slack/basic_usage#using-the-slack-web-api.
