### ISSUE TITLE
Set 'as_user==true' explicitly for all messages sent.

### ISSUE THREAD

**Issue by ArcticSnowman** [slackhq/hubot-slack#336]
* [x] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description
The latest update fixed the issue where `as_user=true` on a crafted message was being mangled.  However prior to 4.x, this value was set explicitly. This is no longer the case and breaks public 3rd party hubot scripts.  

Seems wrong to make script not written for slack, have to include a slack specific work around.

#### Steps to reproduce:

1.  Type 'bot help'

**Comment by DEGoodmanWilson** [comment]
That's fair.

**Comment by DEGoodmanWilson** [comment]
Have a look at #337 @ArcticSnowman ?
