### ISSUE TITLE
How to disable DM responds?

### ISSUE THREAD

**Issue by vetash** [slackhq/hubot-slack#339]
I want to disable hubot in direct messages, how can i do that?

**Comment by rowi1de** [comment]
Just filter the channel:

I'm whitelisting the channels, but you could do a blacklist: "#DM".
```
 # helper method to get channel of originating message
  get_channel = (response) ->
    if response.message.room == response.message.user.name
      "@#{response.message.room}"
    else
      "##{robot.adapter.client.rtm.dataStore.getChannelGroupOrDMById(response.message.room).name}"

# Filter by channel
  channel_to_watch= ['#random']
  robot.hear /(something)/i, (msg) ->
    # limit our annoyance to this channel(s)
    if(get_channel(msg) in channel_to_watch)
      msg.send "we are in #random"


```

**Comment by vetash** [comment]
So i have to change every script for this?

**Comment by vetash** [comment]
I look into `slack.coffee` code and find this:
```      # If this is a DM, pretend it was addressed to us
      if msg.getChannelType() == 'DM'
       text = "#{@robot.name} #{text}"```
So i change it to this:
```      # If this is a DM, pretend it was addressed to us
      if msg.getChannelType() == 'DM'
      #  text = "#{@robot.name} #{text}"
         text = "#{@robot.name} no_respond_on_dm"
```

And create own script which response on `no_respond_on_dm` with message like: 
`Sorry, i'm not response on DM's go to #channel`

M.b. slack team create env variable for this?

**Comment by rowi1de** [comment]
No, You can combine filtering with this:
https://github.com/github/hubot/blob/master/docs/scripting.md#receive-middleware-example

**Comment by vetash** [comment]
@rowi1de  As i described above i've created own workaround, but thanks for the reply anyway! :)
