### ISSUE TITLE
Unable to install - @slack/client missing from NPM?

### ISSUE THREAD

**Issue by bmhatfield** [slackhq/hubot-slack#341]
#### Description
> When I try to NPM install hubot-slack v 4.0.2, it won't install. I observe a 404 in the NPM log related to slack/client.

#### Reproducible in:
hubot-slack version: 4.0.2
OS version(s): Whatever the nodejs:10.25 docker container runs
Device(s): My Mac

#### Steps to reproduce:

1. `npm install hubot-slack`
2. Observe the 404 finding slack/client
3. Be sad that it won't install.

### Expected result:
> I expected that hubot-slack would install.

### Actual result:
> It had an error

### Attachments:
```
npm http GET https://registry.npmjs.org/slack/client
npm http 404 https://registry.npmjs.org/slack/client
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/share/npm/lib/cache.js:687:35)
npm ERR!     at /usr/share/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.4.16-moby
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /hubot
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type non_object_property_load
```

**Comment by mose** [comment]
Your error says `node -v v0.10.25` and `hubot-slack` requires node 0.12 minimum (not sure why, though). If you upgrade your node version it will just work fine.

**Comment by DEGoodmanWilson** [comment]
Closing as solved
