### ISSUE TITLE
[BUG] robot.adapter.customMessage is not a function

### ISSUE THREAD

**Issue by JonathanRosado** [slackhq/hubot-slack#342]
* [x] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description
Function `robot.adapter.customMessage` is no longer available.  

#### Reproducible in:
hubot-slack version: 4.0
OS version(s): ubuntu
Device(s): all

#### Steps to reproduce:

1. call `robot.adapter.customMessage` from your code.

### Attachments:
```
[Wed Aug 17 2016 18:41:26 GMT+0000 (UTC)] ERROR TypeError: robot.adapter.customMessage is not a function
```

**Comment by DEGoodmanWilson** [comment]
Not a bug—we removed that function as being both redundant and error prone. Now if you want to send a message with attachments, you can use the usual message sending mechanisms, and it will all get sorted out automatically for you!

**Comment by dodgepong** [comment]
Forgive me if I'm being dense, but which "usual message sending mechanism" do I use? Can I just run `msg.send myattachment`? I'm having a hard time finding out how to correctly send attachments under 4.0.x.
