### ISSUE TITLE
Reconnect with new token

### ISSUE THREAD

**Issue by aleksei-timofeyev** [slackhq/hubot-slack#343]
Hello!

I need to reconnect to Slack with another bot token.
```
 robot.adapter.client.disconnect()
 robot.adapter.client.rtm._token = NEW_TOKEN_HERE
 robot.adapter.run()
```
After this I have a new bot gets online but with no answers.
Got only this for any received message:
> DEBUG No listeners executed; falling back to catch-all

Is it possible to reconnect to Slack with another token?

Regards, 
Aleksei

**Comment by DEGoodmanWilson** [comment]
Unsure what is going on here, but it looks like your listeners got all disconnected. This is not really a supported use case—probably the best thing to do is to spool up a new process from scratch, TBH.
