### ISSUE TITLE
robot.messageRoom requires channel ID?

### ISSUE THREAD

**Issue by Mezzle** [slackhq/hubot-slack#349]
* [x] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description
> e.g. Description of the bug or feature

#### Reproducible in:
hubot-slack version: 4.0.1/4.0.2
OS version(s): Centos
Device(s): Slack ?

#### Steps to reproduce:

Add the following script to a hubot configured to connect to a slack, with the bot invited to the room `#general`
```coffee
module.exports = (robot) ->
  robot.respond /greet/i, (res) ->
    robot.messageRoom '#general', 'Hi Everybody!'
```

### Expected result:
Send message to #general with "Hi Everybody!"

### Actual result:
```
Unhandled rejection SlackRTMError: invalid channel id
```

This seems to be resolved by using the channel ID (which there doesn't seem to be any convenience functions to find !)

**Comment by DEGoodmanWilson** [comment]
Going to call this fixed ;)
