### ISSUE TITLE
Support For Slack Button

### ISSUE THREAD

**Issue by jcampbell05** [slackhq/hubot-slack#351]
Does this / will this have support for the "Add To Slack" button and how easy is it to add ?

**Comment by DEGoodmanWilson** [comment]
No, this is an adapter for running Hubot. Hubot is a great framework for writing chat-ops bot scripts, but is a terrible framework for distributing a bot app. I strongly recommend you look into BotKit https://howdy.ai/botkit/

**Comment by jcampbell05** [comment]
@DEGoodmanWilson I like BotKit but it lacks the integration support Hubot has. Do you think I could use the two together ?
