### ISSUE TITLE
Bot response does not show bot name or avatar when sending attachments

### ISSUE THREAD

**Issue by dodgepong** [slackhq/hubot-slack#353]
* [x] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description
When sending attachments via `msg.send` using hubot-slack v4.0.2, the bot does not appear to have the bot's avatar or name, but instead has the default bot avatar and the name "bot". When sending normal messages via `msg.send`, the bot has the correct avatar and name.

The bot's name can be changed by setting the `username` parameter on the sent message, but the avatar is still not displayed correctly.

**Example code:**
```
module.exports = (robot) ->
    robot.hear /^test attachments$/i, (msg) ->
        attachment = {
            fallback: 'a test attachment',
            title: 'This is a test attachment',
            text: 'This is attachment text.'
        }
        msg.send
            attachments: [attachment]

    robot.hear /^test messages$/i, (msg) ->
        msg.send 'This is a test message.'
```
**Result:** 
![Image of problem](http://i.imgur.com/NYnAGpj.png)

### Expected result:
I expected `msg.send` to not care if I have attachments or not, but instead be able to appear as coming from the bot that is sending the messages like normal.

**Comment by benpbolton** [comment]
Hey @dodgepong , I think you can accomplish what you'd want by setting as_user to true:

![screen shot 2016-09-07 at 10 09 04 am](https://cloud.githubusercontent.com/assets/7146063/18319496/2e19f776-74e3-11e6-97df-c036799f5b59.png)

...from a line in the [slack docs](https://api.slack.com/bot-users): 

![screen shot 2016-09-07 at 10 09 59 am](https://cloud.githubusercontent.com/assets/7146063/18319525/546ee88c-74e3-11e6-8e20-ceeac4687e5f.png)

I'm unsure why that's not the default, but that did the trick for me!

**Comment by dodgepong** [comment]
Ah, that did it! Thank you! I missed that part of the docs, and was confused because the old way of sending attachments worked fine. Good to know!
