### ISSUE TITLE
Attempting to use emoji as icon or change username of sent message isn't honored?

### ISSUE THREAD

**Issue by MidnightLightning** [slackhq/hubot-slack#359]
#### Description
Cannot set `username` nor `icon_emoji` on Slack messages any more.

This used to be possible, through the `robot.emit 'slack-attachment' messageData` method in v3, but that seems to have gone away in v4.

#### Reproducible in:
hubot-slack version:4.0.5

#### Steps to reproduce:
```coffeescript
robot.hear /./ (res) -> {
  messageData = {
    channel: res.message.room
    username: 'Boaty McBoatface'
    icon_emoji: ':boat:'
    text: 'I\'m on a boat!',
    attachments: [{
      author_name: 'Captain'
      title: 'Captain\'s Log'
      text: 'No land in sight yet...'
    }]
  }
  res.send messageData
  return
```

This structure conforms to Slack's attachment format, and their [online builder](https://api.slack.com/docs/messages/builder?msg=%7B%22text%22%3A%22I%27m%20on%20a%20boat!%22%2C%22icon_emoji%22%3A%22%3Aboat%3A%22%2C%22username%22%3A%22Boaty%20McBoatface%22%2C%22attachments%22%3A%5B%7B%22author_name%22%3A%22Captain%22%2C%22title%22%3A%22Captain%27s%20Log%22%2C%22text%22%3A%22No%20land%20in%20sight%20yet...%22%7D%5D%7D) shows that it should show an emoji avatar and altered username properly.

### Expected result:
In Slack, the message is received, and the avatar of the sender is set to the specified Emoji

### Actual result:
Message is received, but as the Hubot user's typical avatar.

**Comment by DEGoodmanWilson** [comment]
This is almost certainly because we implicitly set `as_user: true` behind the scenes. You'll need to override that setting byutadding `as_user: false` to your payload. Try that and report back?

**Comment by MidnightLightning** [comment]
Yes, adding `as_user:false` did the trick!
