### ISSUE TITLE
upload file

### ISSUE THREAD

**Issue by andrewfsmith** [slackhq/hubot-slack#62]
Is there a way to upload a file to slack?
I see how to send messages and links, but I want to upload a local image as an attachment.
Is this possible?

**Comment by ChrisLundquist** [comment]
After taking a look at https://api.slack.com/methods/files.upload
It looks like there is an error "User is bot", which might be why this never made it into the adapter.
I would guess that using a real user's API token, might be a work around.
<img width="665" alt="screen shot 2015-07-09 at 12 31 51 pm" src="https://cloud.githubusercontent.com/assets/181256/8604976/c92e4584-2636-11e5-9592-52097d21c848.png">

**Comment by victorcoder** [comment]
I asked slack support about this and the recommended way to do it is using a non bot user.

**Comment by technicalpickles** [comment]
cc https://github.com/github/hubot/pull/996 where there's some discussion around adding a method to hubot adapters for uploading files

**Comment by aaronthebaron** [comment]
It looks like they've recently changed this policy and now bot users are allowed to upload files: 
![screen shot 2016-01-05 at 2 24 00 pm](https://cloud.githubusercontent.com/assets/3069310/12129375/0dd932fc-b3b8-11e5-9c19-4f32509fca87.png)

**Comment by santiycr** [comment]
+1

**Comment by jiang-wei** [comment]
+1

**Comment by halkeye** [comment]
I feel like https://github.com/slackhq/node-slack-client/pull/56 should be a priority to get merged, the code is written up it just looks like the PR has fallen silent.

**Comment by halkeye** [comment]
@technicalpickles do we have any sort of standard for uploadFile? or do you want me to make up one like I did for emote?

I have a PR in for https://github.com/crossorigin/node-slack-upload/pull/2 which mostly works anyways, I was going to write a stub/fill for response.uploadFile using that for now.

**Comment by technicalpickles** [comment]
@halkeye there isn't. There is discussion in https://github.com/github/hubot/issues/1036 about more 'types'. I think uploadFile makes sense though.

**Comment by sheluchin** [comment]
+1

**Comment by DEGoodmanWilson** [comment]
This will be fixed in https://github.com/slackhq/hubot-slack/pull/309
